In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('max_colwidth', 100)

In [2]:
# !mkdir ATLAS
# !wget https://atlas.wenglab.org/web/tables/ATLAS.xlsx -O ATLAS/ATLAS.xlsx

In [3]:
df = pd.read_excel("ATLAS/ATLAS.xlsx", dtype=object).drop(columns=['Index'])
print(f"ATLAS database has {len(df)} records has records")
df.head()

ATLAS database has 694 records has records

,TCRname,MHCname,MHCname_PDB,MHC_mut,MHC_mut_chain,TCR_mut,Kd_microM,Kon_per_M_per_s,Koff_per_s,Kd_wt/Kd_mut,DeltaG_kcal_per_mol,Delta_DeltaG_kcal_per_mol,Temperature_K,PEPseq,PEP_mut,true_PDB,Structure_Method,Resolution,R-value,R-free,template_PDB,pMHC_PBID,TCR_mut_chain,CDR,wtCDRseq,TCR_PDB_chain,PMID,Exp. Method,SPR SensorChip,Immobilized Ligand,Coupling Method,Analyte
0,LC13,HLA-B*08:01,HLA-B*08:01,WT,NaN,WT,12.5 +/- 2.1,\N,\N,1,-6.69,\N,298.15,FLRGRAYGL,WT,1MI5,x-ray diffraction,2.5,0.266,0.288,NaN,\N,NaN,\N,\N,\N,15640805,Biacore 3000,CM5,FLRGRAYGL-HLA-B*08:01,direct,LC13 WT
1,LC13,HLA-B*08:01,HLA-B*08:01,WT,NaN,S25A,14.8 +/- 0.55,\N,\N,0.84,-6.59,0.1,298.15,FLRGRAYGL,WT,NaN,\N,\N,\N,\N,1MI5,\N,A,CDR1,TISGTDY,D,15640805,Biacore 3000,CM5,FLRGRAYGL-HLA-B*08:01,direct,LC13 S25A
2,LC13,HLA-B*08:01,HLA-B*08:01,WT,NaN,T26A,19.4 +/- 0.55,\N,\N,0.64,-6.43,0.26,298.15,FLRGRAYGL,WT,NaN,\N,\N,\N,\N,1MI5,\N,A,CDR1,TISGTDY,D,15640805,Biacore 3000,CM5,FLRGRAYGL-HLA-B*08:01,direct,LC13 T26A
3,LC13,HLA-B*08:01,HLA-B*08:01,WT,NaN,S28A,11.7 +/- 0.85,\N,\N,1.07,-6.73,-0.04,298.15,FLRGRAYGL,WT,NaN,\N,\N,\N,\N,1MI5,\N,A,CDR1,TISGTDY,D,15640805,Biacore 3000,CM5,FLRGRAYGL-HLA-B*08:01,direct,LC13 S28A
4,LC13,HLA-B*08:01,HLA-B*08:01,WT,NaN,T30A,33.7 +/- 1.2,\N,\N,0.37,-6.1,0.59,298.15,FLRGRAYGL,WT,NaN,\N,\N,\N,\N,1MI5,\N,A,CDR1,TISGTDY,D,15640805,Biacore 3000,CM5,FLRGRAYGL-HLA-B*08:01,direct,LC13 T30A

In [4]:
with open("ATLAS/0.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['true_PDB'].tolist())]))

## 1. Remove rows without PDB information

In [5]:
df = df.dropna(subset=['true_PDB'])
df['true_PDB'] = df['true_PDB'].str.lower()

print(f"ATLAS database has {len(df)} rows incloud PDB information")
df.head()

ATLAS database has 115 rows incloud PDB information

,TCRname,MHCname,MHCname_PDB,MHC_mut,MHC_mut_chain,TCR_mut,Kd_microM,Kon_per_M_per_s,Koff_per_s,Kd_wt/Kd_mut,DeltaG_kcal_per_mol,Delta_DeltaG_kcal_per_mol,Temperature_K,PEPseq,PEP_mut,true_PDB,Structure_Method,Resolution,R-value,R-free,template_PDB,pMHC_PBID,TCR_mut_chain,CDR,wtCDRseq,TCR_PDB_chain,PMID,Exp. Method,SPR SensorChip,Immobilized Ligand,Coupling Method,Analyte
0,LC13,HLA-B*08:01,HLA-B*08:01,WT,NaN,WT,12.5 +/- 2.1,\N,\N,1,-6.69,\N,298.15,FLRGRAYGL,WT,1mi5,x-ray diffraction,2.5,0.266,0.288,NaN,\N,NaN,\N,\N,\N,15640805,Biacore 3000,CM5,FLRGRAYGL-HLA-B*08:01,direct,LC13 WT
39,JM22,HLA-A*02:01,HLA-A*02:01,WT,NaN,WT,5.2,31000,0.16,1,-7.21,\N,298.15,GILGFVFTL,WT,2vlj,x-ray diffraction,2.4,0.2,0.272,NaN,\N,NaN,\N,\N,\N,18275829,Biacore 2000,CM5,GILGFVFTL-HLA-A*02:01,indirect,JM22 WT
59,JM22,HLA-A*02:01,HLA-A*02:01,WT,NaN,S99A,4.9,59000,0.29,1.06,-7.24,-0.03,298.15,GILGFVFTL,WT,2vlr,x-ray diffraction,2.3,0.222,0.281,2VLJ,\N,B,CDR3,ASSSRSSYEQY,E,18275829,Biacore 2000,CM5,GILGFVFTL-HLA-A*02:01,indirect,JM22 S99A
62,A6,HLA-A*02:01,HLA-A*02:01,WT,NaN,WT,2.113503,51100,0.108,1,-7.74,\N,298.15,LLFGYPVYV,WT,1ao7,x-ray diffraction,2.6,0.245,0.32,NaN,\N,NaN,\N,\N,\N,18767161,Biacore 3000,CM5,A6 WT,direct,LLFGYPVYV-HLA-A*02:01
89,RA14,HLA-A*02:01,HLA-A*02:01,WT,NaN,WT,27.7 +/- 2.3,\N,\N,1,-6.21,\N,298.15,NLVPMVATV,WT,3gsn,x-ray diffraction,2.8,0.237,0.29,NaN,3GSO,NaN,\N,\N,\N,19542454,Biacore 3000,CM5,RA14 WT,direct,NLVPMVATV-HLA-A*02:01

In [6]:
with open("ATLAS/1.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['true_PDB'].tolist())]))

## 2. PDB drop duplicates

In [7]:
df = df.drop_duplicates(subset=['true_PDB'])
print(f"ATLAS database has: {len(df)} unique PDB")
df.head()

ATLAS database has: 87 unique PDB

,TCRname,MHCname,MHCname_PDB,MHC_mut,MHC_mut_chain,TCR_mut,Kd_microM,Kon_per_M_per_s,Koff_per_s,Kd_wt/Kd_mut,DeltaG_kcal_per_mol,Delta_DeltaG_kcal_per_mol,Temperature_K,PEPseq,PEP_mut,true_PDB,Structure_Method,Resolution,R-value,R-free,template_PDB,pMHC_PBID,TCR_mut_chain,CDR,wtCDRseq,TCR_PDB_chain,PMID,Exp. Method,SPR SensorChip,Immobilized Ligand,Coupling Method,Analyte
0,LC13,HLA-B*08:01,HLA-B*08:01,WT,NaN,WT,12.5 +/- 2.1,\N,\N,1,-6.69,\N,298.15,FLRGRAYGL,WT,1mi5,x-ray diffraction,2.5,0.266,0.288,NaN,\N,NaN,\N,\N,\N,15640805,Biacore 3000,CM5,FLRGRAYGL-HLA-B*08:01,direct,LC13 WT
39,JM22,HLA-A*02:01,HLA-A*02:01,WT,NaN,WT,5.2,31000,0.16,1,-7.21,\N,298.15,GILGFVFTL,WT,2vlj,x-ray diffraction,2.4,0.2,0.272,NaN,\N,NaN,\N,\N,\N,18275829,Biacore 2000,CM5,GILGFVFTL-HLA-A*02:01,indirect,JM22 WT
59,JM22,HLA-A*02:01,HLA-A*02:01,WT,NaN,S99A,4.9,59000,0.29,1.06,-7.24,-0.03,298.15,GILGFVFTL,WT,2vlr,x-ray diffraction,2.3,0.222,0.281,2VLJ,\N,B,CDR3,ASSSRSSYEQY,E,18275829,Biacore 2000,CM5,GILGFVFTL-HLA-A*02:01,indirect,JM22 S99A
62,A6,HLA-A*02:01,HLA-A*02:01,WT,NaN,WT,2.113503,51100,0.108,1,-7.74,\N,298.15,LLFGYPVYV,WT,1ao7,x-ray diffraction,2.6,0.245,0.32,NaN,\N,NaN,\N,\N,\N,18767161,Biacore 3000,CM5,A6 WT,direct,LLFGYPVYV-HLA-A*02:01
89,RA14,HLA-A*02:01,HLA-A*02:01,WT,NaN,WT,27.7 +/- 2.3,\N,\N,1,-6.21,\N,298.15,NLVPMVATV,WT,3gsn,x-ray diffraction,2.8,0.237,0.29,NaN,3GSO,NaN,\N,\N,\N,19542454,Biacore 3000,CM5,RA14 WT,direct,NLVPMVATV-HLA-A*02:01

In [8]:
with open("ATLAS/2.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['true_PDB'].tolist())]))

## 3. Keep human MHC

In [9]:
df = df.loc[df['MHCname'].str.upper().str[:3]=='HLA']
print(f"ATLAS database has: {len(df)} unique human PDB")
df.head()

ATLAS database has: 69 unique human PDB

,TCRname,MHCname,MHCname_PDB,MHC_mut,MHC_mut_chain,TCR_mut,Kd_microM,Kon_per_M_per_s,Koff_per_s,Kd_wt/Kd_mut,DeltaG_kcal_per_mol,Delta_DeltaG_kcal_per_mol,Temperature_K,PEPseq,PEP_mut,true_PDB,Structure_Method,Resolution,R-value,R-free,template_PDB,pMHC_PBID,TCR_mut_chain,CDR,wtCDRseq,TCR_PDB_chain,PMID,Exp. Method,SPR SensorChip,Immobilized Ligand,Coupling Method,Analyte
0,LC13,HLA-B*08:01,HLA-B*08:01,WT,NaN,WT,12.5 +/- 2.1,\N,\N,1,-6.69,\N,298.15,FLRGRAYGL,WT,1mi5,x-ray diffraction,2.5,0.266,0.288,NaN,\N,NaN,\N,\N,\N,15640805,Biacore 3000,CM5,FLRGRAYGL-HLA-B*08:01,direct,LC13 WT
39,JM22,HLA-A*02:01,HLA-A*02:01,WT,NaN,WT,5.2,31000,0.16,1,-7.21,\N,298.15,GILGFVFTL,WT,2vlj,x-ray diffraction,2.4,0.2,0.272,NaN,\N,NaN,\N,\N,\N,18275829,Biacore 2000,CM5,GILGFVFTL-HLA-A*02:01,indirect,JM22 WT
59,JM22,HLA-A*02:01,HLA-A*02:01,WT,NaN,S99A,4.9,59000,0.29,1.06,-7.24,-0.03,298.15,GILGFVFTL,WT,2vlr,x-ray diffraction,2.3,0.222,0.281,2VLJ,\N,B,CDR3,ASSSRSSYEQY,E,18275829,Biacore 2000,CM5,GILGFVFTL-HLA-A*02:01,indirect,JM22 S99A
62,A6,HLA-A*02:01,HLA-A*02:01,WT,NaN,WT,2.113503,51100,0.108,1,-7.74,\N,298.15,LLFGYPVYV,WT,1ao7,x-ray diffraction,2.6,0.245,0.32,NaN,\N,NaN,\N,\N,\N,18767161,Biacore 3000,CM5,A6 WT,direct,LLFGYPVYV-HLA-A*02:01
89,RA14,HLA-A*02:01,HLA-A*02:01,WT,NaN,WT,27.7 +/- 2.3,\N,\N,1,-6.21,\N,298.15,NLVPMVATV,WT,3gsn,x-ray diffraction,2.8,0.237,0.29,NaN,3GSO,NaN,\N,\N,\N,19542454,Biacore 3000,CM5,RA14 WT,direct,NLVPMVATV-HLA-A*02:01

In [10]:
df['true_PDB'].rename('ATLAS').to_csv('ATLAS/ATLAS_pdb.csv', index=False)

In [11]:
with open("ATLAS/3.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['true_PDB'].tolist())]))

In [12]:
df[['true_PDB', 'MHCname']].rename(columns={'true_PDB':'pdb', 'MHCname': 'TRAIT_MHCname'}).set_index('pdb').to_csv('ATLAS/ATLAS_hla.csv')