In [14]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('max_colwidth', 100)

In [15]:
# !mkdir IEDB
# !wget https://www.iedb.org/downloader.php?file_name=doc/tcell_full_v3.zip -P IEDB
# !unzip IEDB/tcell_full_v3.zip -d IEDB/

In [16]:
df = pd.read_csv("IEDB/tcell_full_v3.csv", header=[0,1], dtype=object)
print(f"IEDB database has {len(df)} records has records")
df.head()

IEDB database has 543305 records has records

                       Assay ID                          Reference  \
                       IEDB IRI                           IEDB IRI
0  http://www.iedb.org/assay/29  http://www.iedb.org/reference/274
1  http://www.iedb.org/assay/37  http://www.iedb.org/reference/281
2  http://www.iedb.org/assay/42  http://www.iedb.org/reference/283
3  http://www.iedb.org/assay/43  http://www.iedb.org/reference/283
4  http://www.iedb.org/assay/47  http://www.iedb.org/reference/275

                                       \
         Type      PMID Submission ID
0  Literature  15448372           NaN
1  Literature   7684468           NaN
2  Literature  15634878           NaN
3  Literature  15634878           NaN
4  Literature  15519708           NaN

                                                                                                        \
                                                                                               Authors
0                                   Yi-Hsiang Huang; Mi-Hua Tao; Cheng-Po Hu; Wan-Jr Syu; Jaw-Ching Wu
1                                                   V J La Posta; D D Auperin; R Kamin-Lewis; G A Cole
2                                                      Evan R Jellison; Sung-Kwon Kim; Raymond M Welsh
3                                                      Evan R Jellison; Sung-Kwon Kim; Raymond M Welsh
4  Olivier B Engler; Reto A Schwendener; Wen Juan Dai; Benno Wölk; Werner Pichler; Darius Moradpour...

                      \
       Journal  Date
0  J Gen Virol  2004
1      J Virol  1993
2    J Immunol  2005
3    J Immunol  2005
4      Vaccine  2004

                                                                                                        \
                                                                                                 Title
0         Identification of novel HLA-A*0201-restricted CD8+ T-cell epitopes on hepatitis delta virus.
1  Cross-protection against lymphocytic choriomeningitis virus mediated by a CD4+ T-cell clone spec...
2                        Cutting edge: MHC class II-restricted killing in vivo during viral infection.
3                        Cutting edge: MHC class II-restricted killing in vivo during viral infection.
4  A liposomal peptide vaccine inducing CD8+ T cells in HLA-A2.1 transgenic mice, which recognise h...

                             Epitope                                        \
                            IEDB IRI     Object Type                  Name
0  http://www.iedb.org/epitope/31803  Linear peptide             KLEDLERDL
1  http://www.iedb.org/epitope/25946  Linear peptide       IEQQADNMITEMLQK
2  http://www.iedb.org/epitope/21045  Linear peptide  GLNGPDIYKGVYQFKSVEFD
3  http://www.iedb.org/epitope/58012  Linear peptide  SGEGWPYIACRTSVVGRAWE
4   http://www.iedb.org/epitope/9203  Linear peptide             DLMGYIPLV

                                                                    \
  Reference Name Modified residues Modifications Starting Position
0      HDV 26-34               NaN           NaN                26
1     GP 403-417               NaN           NaN               403
2       GP 61-80               NaN           NaN                61
3     NP 309-328               NaN           NaN               309
4       Core 132               NaN           NaN               132

                                                                          \
  Ending Position  IRI Synonyms                          Source Molecule
0              34  NaN      NaN                      large delta antigen
1             417  NaN      NaN                 Glycoprotein polyprotein
2              80  NaN      NaN  Pre-glycoprotein polyprotein GP complex
3             328  NaN      NaN                            Nucleoprotein
4             140  NaN      NaN                       Genome polyprotein

                                                   \
                              Source Molecule IRI
0  http://www.ncbi.nlm.nih.gov/protein/AAG26087.1
1    http://www.ncbi.nlm.nih.gov/protein/P08669.1
2        https://www.uniprot.org/uniprot/P07399.1
3    http://www.ncbi.nlm.nih.gov/protein/P07400.1
4        https://www.uniprot.org/uniprot/P26664.3

                                            \
                           Molecule Parent
0                      Large delta antigen
1  Pre-glycoprotein polyprotein GP complex
2  Pre-glycoprotein polyprotein GP complex
3                            Nucleoprotein
4                       Genome polyprotein

                                          \
                     Molecule Parent IRI
0  http://www.uniprot.org/uniprot/P29996
1  http://www.uniprot.org/uniprot/P08669
2  http://www.uniprot.org/uniprot/P09991
3  http://www.uniprot.org/uniprot/P09992
4  http://www.uniprot.org/uniprot/P27958

                                                          \
                                         Source Organism
0                           Hepatitis delta virus TW2667
1                               Mammarenavirus lassaense
2  Lymphocytic choriomeningitis virus (strain Armstrong)
3  Lymphocytic choriomeningitis virus (strain Armstrong)
4                          hepatitis C virus genotype 1a

                                                     \
                                Source Organism IRI
0  https://ontology.iedb.org/ontology/ONTIE_0000432
1  http://purl.obolibrary.org/obo/NCBITaxon_3052310
2    http://purl.obolibrary.org/obo/NCBITaxon_11624
3    http://purl.obolibrary.org/obo/NCBITaxon_11624
4  http://purl.obolibrary.org/obo/NCBITaxon_2847144

                                      \
                             Species
0              Hepatitis delta virus
1           Mammarenavirus lassaense
2  Mammarenavirus choriomeningitidis
3  Mammarenavirus choriomeningitidis
4                Hepacivirus hominis

                                                                      \
                                        Species IRI Epitope Comments
0    http://purl.obolibrary.org/obo/NCBITaxon_12475              NaN
1  http://purl.obolibrary.org/obo/NCBITaxon_3052310              NaN
2  http://purl.obolibrary.org/obo/NCBITaxon_3052303              NaN
3  http://purl.obolibrary.org/obo/NCBITaxon_3052303              NaN
4  http://purl.obolibrary.org/obo/NCBITaxon_3052230              NaN

    Related Object                                                          \
  Epitope Relation Object Type Name Starting Position Ending Position  IRI
0              NaN         NaN  NaN               NaN             NaN  NaN
1              NaN         NaN  NaN               NaN             NaN  NaN
2              NaN         NaN  NaN               NaN             NaN  NaN
3              NaN         NaN  NaN               NaN             NaN  NaN
4              NaN         NaN  NaN               NaN             NaN  NaN

                                                                \
  Synonyms Source Molecule Source Molecule IRI Molecule Parent
0      NaN             NaN                 NaN             NaN
1      NaN             NaN                 NaN             NaN
2      NaN             NaN                 NaN             NaN
3      NaN             NaN                 NaN             NaN
4      NaN             NaN                 NaN             NaN

                                                                               \
  Molecule Parent IRI Source Organism Source Organism IRI Species Species IRI
0                 NaN             NaN                 NaN     NaN         NaN
1                 NaN             NaN                 NaN     NaN         NaN
2                 NaN             NaN                 NaN     NaN         NaN
3                 NaN             NaN                 NaN     NaN         NaN
4                 NaN             NaN                 NaN     NaN         NaN

                          Host  \
                          Name
0       Mus musculus HLA-A2 Tg
1          Mus musculus C3H/He
2         Mus musculus C57BL/6
3         Mus musculus C57BL/6
4  Mus musculus HLA-A*02:01 Tg

                                                                 \
                                                IRI Geolocation
0  https://ontology.iedb.org/ontology/ONTIE_0000490         NaN
1  https://ontology.iedb.org/ontology/ONTIE_0000037         NaN
2  https://ontology.iedb.org/ontology/ONTIE_0000062         NaN
3  https://ontology.iedb.org/ontology/ONTIE_0000062         NaN
4  https://ontology.iedb.org/ontology/ONTIE_0000484         NaN

                                                   1st in vivo Process  \
  Geolocation IRI  Sex         Age MHC Present            Process Type
0             NaN  NaN  8-10 weeks         NaN  Administration in vivo
1             NaN    F  6-12 weeks         NaN  Administration in vivo
2             NaN  NaN         NaN         NaN  Administration in vivo
3             NaN  NaN         NaN         NaN  Administration in vivo
4             NaN  NaN   6-8 weeks         NaN  Administration in vivo

                                       1st immunogen                  \
  Disease Disease IRI Disease Stage Epitope Relation     Object Type
0     NaN         NaN           NaN   Source Antigen         Protein
1     NaN         NaN           NaN   Source Antigen         Protein
2     NaN         NaN           NaN  Source Organism        Organism
3     NaN         NaN           NaN  Source Organism        Organism
4     NaN         NaN           NaN          Epitope  Linear peptide

                                                          \
                                                    Name
0                                    large delta antigen
1                               Glycoprotein polyprotein
2  Lymphocytic choriomeningitis virus (strain Armstrong)
3  Lymphocytic choriomeningitis virus (strain Armstrong)
4                                              DLMGYIPLV

                                                               \
             Reference Name Starting Position Ending Position
0        p2667L DNA vaccine               NaN             NaN
1  Glycoprotein polyprotein               NaN             NaN
2                       NaN               NaN             NaN
3                       NaN               NaN             NaN
4                  Core 132               132             140

                                                                       \
                                              IRI     Source Molecule
0  http://www.ncbi.nlm.nih.gov/protein/AAG26087.1                 NaN
1    http://www.ncbi.nlm.nih.gov/protein/P08669.1                 NaN
2                                             NaN                 NaN
3                                             NaN                 NaN
4                                             NaN  Genome polyprotein

                                                                 \
                        Source Molecule IRI     Molecule Parent
0                                       NaN                 NaN
1                                       NaN                 NaN
2                                       NaN                 NaN
3                                       NaN                 NaN
4  https://www.uniprot.org/uniprot/P26664.3  Genome polyprotein

                                          \
                     Molecule Parent IRI
0                                    NaN
1                                    NaN
2                                    NaN
3                                    NaN
4  http://www.uniprot.org/uniprot/P27958

                                                          \
                                         Source Organism
0                           Hepatitis delta virus TW2667
1                               Mammarenavirus lassaense
2  Lymphocytic choriomeningitis virus (strain Armstrong)
3  Lymphocytic choriomeningitis virus (strain Armstrong)
4                          hepatitis C virus genotype 1a

                                                     \
                                Source Organism IRI
0          https://ontology.iedb.org/taxon/10000523
1  http://purl.obolibrary.org/obo/NCBITaxon_3052310
2    http://purl.obolibrary.org/obo/NCBITaxon_11624
3    http://purl.obolibrary.org/obo/NCBITaxon_11624
4  http://purl.obolibrary.org/obo/NCBITaxon_2847144

                                      \
                             Species
0              Hepatitis delta virus
1           Mammarenavirus lassaense
2  Mammarenavirus choriomeningitidis
3  Mammarenavirus choriomeningitidis
4                Hepacivirus hominis

                                                                          \
                                        Species IRI            Adjuvants
0    http://purl.obolibrary.org/obo/NCBITaxon_12475                  NaN
1  http://purl.obolibrary.org/obo/NCBITaxon_3052310  ;Freund's complete;
2  http://purl.obolibrary.org/obo/NCBITaxon_3052303                  NaN
3  http://purl.obolibrary.org/obo/NCBITaxon_3052303                  NaN
4  http://purl.obolibrary.org/obo/NCBITaxon_3052230          ;Liposomes;

                    \
             Route
0    intramuscular
1  intraperitoneal
2  intraperitoneal
3  intraperitoneal
4     subcutaneous

                                                                                                        \
                                                                                         Dose Schedule
0                                               3 doses of 10 µg DNA, administered at weeks 0, 3 and 6
1                                                                                                    1
2                                                                                                  NaN
3                                                                                                  NaN
4  Mice received 3 immunizations at 2-wk intervals of  the liposome formulation containing about 13...

  2nd in vivo Process                                      2nd immunogen  \
         Process Type Disease Disease IRI Disease Stage Epitope Relation
0                 NaN     NaN         NaN           NaN              NaN
1                 NaN     NaN         NaN           NaN              NaN
2                 NaN     NaN         NaN           NaN              NaN
3                 NaN     NaN         NaN           NaN              NaN
4                 NaN     NaN         NaN           NaN              NaN

                                                                          \
  Object Type Name Reference Name Starting Position Ending Position  IRI
0         NaN  NaN            NaN               NaN             NaN  NaN
1         NaN  NaN            NaN               NaN             NaN  NaN
2         NaN  NaN            NaN               NaN             NaN  NaN
3         NaN  NaN            NaN               NaN             NaN  NaN
4         NaN  NaN            NaN               NaN             NaN  NaN

                                                                           \
  Source Molecule Source Molecule IRI Molecule Parent Molecule Parent IRI
0             NaN                 NaN             NaN                 NaN
1             NaN                 NaN             NaN                 NaN
2             NaN                 NaN             NaN                 NaN
3             NaN                 NaN             NaN                 NaN
4             NaN                 NaN             NaN                 NaN

                                                                           \
  Source Organism Source Organism IRI Species Species IRI Adjuvants Route
0             NaN                 NaN     NaN         NaN       NaN   NaN
1             NaN                 NaN     NaN         NaN       NaN   NaN
2             NaN                 NaN     NaN         NaN       NaN   NaN
3             NaN                 NaN     NaN         NaN       NaN   NaN
4             NaN                 NaN     NaN         NaN       NaN   NaN

                       In vitro Process in vitro Responder Cell  \
  Dose Schedule            Process Type                    Name
0           NaN                     NaN                     NaN
1           NaN                     NaN                     NaN
2           NaN                     NaN                     NaN
3           NaN                     NaN                     NaN
4           NaN  Restimulation in vitro              Splenocyte

                                             in vitro Stimulator Cell  \
                                         IRI                     Name
0                                        NaN                      NaN
1                                        NaN                      NaN
2                                        NaN                      NaN
3                                        NaN                      NaN
4  http://purl.obolibrary.org/obo/CL_2000074               Splenocyte

                                             in vitro immunogen  \
                                         IRI   Epitope Relation
0                                        NaN                NaN
1                                        NaN                NaN
2                                        NaN                NaN
3                                        NaN                NaN
4  http://purl.obolibrary.org/obo/CL_2000074            Epitope

                                                                               \
      Object Type       Name Reference Name Starting Position Ending Position
0             NaN        NaN            NaN               NaN             NaN
1             NaN        NaN            NaN               NaN             NaN
2             NaN        NaN            NaN               NaN             NaN
3             NaN        NaN            NaN               NaN             NaN
4  Linear peptide  DLMGYIPLV            NaN               132             140

                                                                      \
   IRI     Source Molecule                       Source Molecule IRI
0  NaN                 NaN                                       NaN
1  NaN                 NaN                                       NaN
2  NaN                 NaN                                       NaN
3  NaN                 NaN                                       NaN
4  NaN  Genome polyprotein  https://www.uniprot.org/uniprot/P26664.3

                                                              \
      Molecule Parent                    Molecule Parent IRI
0                 NaN                                    NaN
1                 NaN                                    NaN
2                 NaN                                    NaN
3                 NaN                                    NaN
4  Genome polyprotein  http://www.uniprot.org/uniprot/P27958

                                  \
                 Source Organism
0                            NaN
1                            NaN
2                            NaN
3                            NaN
4  hepatitis C virus genotype 1a

                                                                          \
                                Source Organism IRI              Species
0                                               NaN                  NaN
1                                               NaN                  NaN
2                                               NaN                  NaN
3                                               NaN                  NaN
4  http://purl.obolibrary.org/obo/NCBITaxon_2847144  Hepacivirus hominis

                                                    Adoptive Transfer  \
                                        Species IRI              Flag
0                                               NaN                 N
1                                               NaN                 N

In [17]:
with open("IEDB/0.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df[('Complex', 'PDB ID')].tolist())]))

## 1. PDB Filter

In [18]:
df = df.dropna(subset=[('Complex', 'PDB ID')])
df = df.loc[(df[('Epitope', 'Object Type')] == 'Linear peptide') & (df[('Assay', 'Qualitative Measurement')] == 'Positive')]
df = df.loc[df[('Complex', 'PDB ID')].str.len()==4]
df[('Complex', 'PDB ID')] = df[('Complex', 'PDB ID')].str.lower()

print(f"IEDB database has {len(df)} rows incloud PDB information")
df.head()

IEDB database has 310 rows incloud PDB information

                                Assay ID  \
                                IEDB IRI
7117   http://www.iedb.org/assay/1005001
7126   http://www.iedb.org/assay/1005014
7127   http://www.iedb.org/assay/1005016
65227  http://www.iedb.org/assay/1404662
79655  http://www.iedb.org/assay/1478873

                                   Reference                        \
                                    IEDB IRI        Type      PMID
7117   http://www.iedb.org/reference/1000291  Literature  12796775
7126   http://www.iedb.org/reference/1000293  Literature  11060013
7127   http://www.iedb.org/reference/1000294  Literature  11877480
65227  http://www.iedb.org/reference/1004650  Literature  12530975
79655  http://www.iedb.org/reference/1008126  Literature   9586631

                     \
      Submission ID
7117            NaN
7126            NaN
7127            NaN
65227           NaN
79655           NaN

                                                                                                            \
                                                                                                   Authors
7117          Guillaume B E Stewart-Jones; Andrew J McMichael; John I Bell; David I Stuart; E Yvonne Jones
7126                                                                        J Hennecke; A Carfi; D C Wiley
7127                                                                            Jens Hennecke; Don C Wiley
65227  Lars Kjer-Nielsen; Craig S Clements; Anthony W Purcell; Andrew G Brooks; James C Whisstock; Scot...
79655                                    Y H Ding; K J Smith; D N Garboczi; U Utz; W E Biddison; D C Wiley

                          \
           Journal  Date
7117   Nat Immunol  2003
7126        EMBO J  2000
7127     J Exp Med  2002
65227     Immunity  2003
79655     Immunity  1998

                                                                                                            \
                                                                                                     Title
7117                              A structural basis for immunodominant human T cell receptor recognition.
7126   Structure of a covalently stabilized complex of a human alphabeta T-cell receptor, influenza HA ...
7127   Structure of a complex of the human alpha/beta T cell receptor (TCR) HA1.7, influenza hemaggluti...
65227   A structural basis for the selection of dominant alphabeta T cell receptors in antiviral immunity.
79655  Two human T cell receptors bind in a similar diagonal mode to the HLA-A2/Tax peptide complex usi...

                                 Epitope                                 \
                                IEDB IRI     Object Type           Name
7117   http://www.iedb.org/epitope/20354  Linear peptide      GILGFVFTL
7126   http://www.iedb.org/epitope/48237  Linear peptide  PKYVKQNTLKLAT
7127   http://www.iedb.org/epitope/48237  Linear peptide  PKYVKQNTLKLAT
65227  http://www.iedb.org/epitope/16878  Linear peptide      FLRGRAYGL
79655  http://www.iedb.org/epitope/37257  Linear peptide      LLFGYPVYV

                                                                            \
                                          Reference Name Modified residues
7117   influenza A virus matrix protein M1 peptide 58-66               NaN
7126             influenza hemagglutinin 306-318 peptide               NaN
7127            influenza haemagglutinin 306-318 peptide               NaN
65227                                       EBNA-3 11-19               NaN
79655                                  Tax peptide 11-19               NaN

                                                                     \
      Modifications Starting Position Ending Position  IRI Synonyms
7117            NaN                58              66  NaN      NaN
7126            NaN               322             334  NaN      NaN
7127            NaN               322             334  NaN      NaN
65227           NaN                11              19  NaN      NaN
79655           NaN                11              19  NaN      NaN

                                      \
                     Source Molecule
7117                Matrix protein 1
7126         Hemagglutinin precursor
7127         Hemagglutinin precursor
65227         nuclear antigen EBNA-3
79655  transcriptional activator Tax

                                                       \
                                  Source Molecule IRI
7117         https://www.uniprot.org/uniprot/P03485.1
7126     http://www.ncbi.nlm.nih.gov/protein/P03437.1
7127     http://www.ncbi.nlm.nih.gov/protein/P03437.1
65227  http://www.ncbi.nlm.nih.gov/protein/AAB20988.1
79655  http://www.ncbi.nlm.nih.gov/protein/AAG31572.1

                                                                              \
                      Molecule Parent                    Molecule Parent IRI
7117                 Matrix protein 1  http://www.uniprot.org/uniprot/P03485
7126                    Hemagglutinin  http://www.uniprot.org/uniprot/P03452
7127                    Hemagglutinin  http://www.uniprot.org/uniprot/P03452
65227  Epstein-Barr nuclear antigen 3  http://www.uniprot.org/uniprot/P12977
79655                   Protein Tax-1  http://www.uniprot.org/uniprot/P14079

                                                 \
                                Source Organism
7117                          Influenza A virus
7126   Influenza A virus (A/Aichi/2/1968(H3N2))
7127   Influenza A virus (A/Aichi/2/1968(H3N2))
65227                  human gammaherpesvirus 4
79655        Human T-cell leukemia virus type I

                                                        \
                                   Source Organism IRI
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320
7126   http://purl.obolibrary.org/obo/NCBITaxon_387139
7127   http://purl.obolibrary.org/obo/NCBITaxon_387139
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376
79655   http://purl.obolibrary.org/obo/NCBITaxon_11908

                                       \
                              Species
7117                Influenza A virus
7126                Influenza A virus
7127                Influenza A virus
65227        human gammaherpesvirus 4
79655  Primate T-lymphotropic virus 1

                                                                         \
                                           Species IRI Epitope Comments
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320              NaN
7126    http://purl.obolibrary.org/obo/NCBITaxon_11320              NaN
7127    http://purl.obolibrary.org/obo/NCBITaxon_11320              NaN
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376              NaN
79655  http://purl.obolibrary.org/obo/NCBITaxon_194440              NaN

        Related Object                                                     \
      Epitope Relation Object Type Name Starting Position Ending Position
7117               NaN         NaN  NaN               NaN             NaN
7126               NaN         NaN  NaN               NaN             NaN
7127               NaN         NaN  NaN               NaN             NaN
65227              NaN         NaN  NaN               NaN             NaN
79655              NaN         NaN  NaN               NaN             NaN

                                                                         \
       IRI Synonyms Source Molecule Source Molecule IRI Molecule Parent
7117   NaN      NaN             NaN                 NaN             NaN
7126   NaN      NaN             NaN                 NaN             NaN
7127   NaN      NaN             NaN                 NaN             NaN
65227  NaN      NaN             NaN                 NaN             NaN
79655  NaN      NaN             NaN                 NaN             NaN

                                                                       \
      Molecule Parent IRI Source Organism Source Organism IRI Species
7117                  NaN             NaN                 NaN     NaN
7126                  NaN             NaN                 NaN     NaN
7127                  NaN             NaN                 NaN     NaN
65227                 NaN             NaN                 NaN     NaN
79655                 NaN             NaN                 NaN     NaN

                                   Host  \
      Species IRI                  Name
7117          NaN  Homo sapiens (human)
7126          NaN  Homo sapiens (human)
7127          NaN  Homo sapiens (human)
65227         NaN  Homo sapiens (human)
79655         NaN  Homo sapiens (human)

                                                                  \
                                                 IRI Geolocation
7117   http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
7126   http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
7127   http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
65227  http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
79655  http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN

                                             \
      Geolocation IRI  Sex  Age MHC Present
7117              NaN  NaN  NaN         NaN
7126              NaN  NaN  NaN         NaN
7127              NaN  NaN  NaN         NaN
65227             NaN  NaN  NaN         NaN
79655             NaN  NaN  NaN         NaN

                                                                   1st in vivo Process  \
                                                                          Process Type
7117   Environmental exposure to endemic/ubiquitous agent without evidence for disease
7126             Exposure with existing immune reactivity without evidence for disease
7127                                                                           Unknown
65227  Environmental exposure to endemic/ubiquitous agent without evidence for disease
79655                                                 Occurrence of infectious disease

                                                                              \
                            Disease                              Disease IRI
7117                            NaN                                      NaN
7126                            NaN                                      NaN
7127                            NaN                                      NaN
65227                           NaN                                      NaN
79655  tropical spastic paraparesis  http://purl.obolibrary.org/obo/DOID_321

                         1st immunogen              \
      Disease Stage   Epitope Relation Object Type
7117            NaN    Source Organism    Organism
7126            NaN  Taxonomic Sibling    Organism
7127            NaN                NaN         NaN
65227           NaN    Source Organism    Organism
79655       Chronic    Source Organism    Organism

                                                                                           \
                                                                                     Name
7117                                                                    Influenza A virus
7126   Influenza A virus (A/Texas/1/1977(H3N2)) (Influenza A virus (A/Texas/1/77 (H3N2)))
7127                                                                                  NaN
65227                                            Human herpesvirus 4 (Epstein Barr virus)
79655             Human T-cell leukemia virus type I (Human T cell leukemia virus type 1)

                                                                   \
            Reference Name Starting Position Ending Position  IRI
7117                   NaN               NaN             NaN  NaN
7126                   NaN               NaN             NaN  NaN
7127                   NaN               NaN             NaN  NaN
65227  Human herpesvirus 4               NaN             NaN  NaN
79655                  NaN               NaN             NaN  NaN

                                                                               \
      Source Molecule Source Molecule IRI Molecule Parent Molecule Parent IRI
7117              NaN                 NaN             NaN                 NaN
7126              NaN                 NaN             NaN                 NaN
7127              NaN                 NaN             NaN                 NaN
65227             NaN                 NaN             NaN                 NaN
79655             NaN                 NaN             NaN                 NaN

                                                 \
                                Source Organism
7117                          Influenza A virus
7126   Influenza A virus (A/Texas/1/1977(H3N2))
7127                                        NaN
65227                  human gammaherpesvirus 4
79655        Human T-cell leukemia virus type I

                                                        \
                                   Source Organism IRI
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320
7126   http://purl.obolibrary.org/obo/NCBITaxon_444318
7127                                               NaN
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376
79655   http://purl.obolibrary.org/obo/NCBITaxon_11908

                                       \
                              Species
7117                Influenza A virus
7126                Influenza A virus
7127                              NaN
65227        human gammaherpesvirus 4
79655  Primate T-lymphotropic virus 1

                                                                        \
                                           Species IRI Adjuvants Route
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320       NaN   NaN
7126    http://purl.obolibrary.org/obo/NCBITaxon_11320       NaN   NaN
7127                                               NaN       NaN   NaN
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376       NaN   NaN
79655  http://purl.obolibrary.org/obo/NCBITaxon_194440       NaN   NaN

                    2nd in vivo Process                                    \
      Dose Schedule        Process Type Disease Disease IRI Disease Stage
7117            NaN                 NaN     NaN         NaN           NaN
7126            NaN                 NaN     NaN         NaN           NaN
7127            NaN                 NaN     NaN         NaN           NaN
65227           NaN                 NaN     NaN         NaN           NaN
79655           NaN                 NaN     NaN         NaN           NaN

         2nd immunogen                                                    \
      Epitope Relation Object Type Name Reference Name Starting Position
7117               NaN         NaN  NaN            NaN               NaN
7126               NaN         NaN  NaN            NaN               NaN
7127               NaN         NaN  NaN            NaN               NaN
65227              NaN         NaN  NaN            NaN               NaN
79655              NaN         NaN  NaN            NaN               NaN

                                                                \
      Ending Position  IRI Source Molecule Source Molecule IRI
7117              NaN  NaN             NaN                 NaN
7126              NaN  NaN             NaN                 NaN
7127              NaN  NaN             NaN                 NaN
65227             NaN  NaN             NaN                 NaN
79655             NaN  NaN             NaN                 NaN

                                                                               \
      Molecule Parent Molecule Parent IRI Source Organism Source Organism IRI
7117              NaN                 NaN             NaN                 NaN
7126              NaN                 NaN             NaN                 NaN
7127              NaN                 NaN             NaN                 NaN
65227             NaN                 NaN             NaN                 NaN
79655             NaN                 NaN             NaN                 NaN

                                                         \
      Species Species IRI Adjuvants Route Dose Schedule
7117      NaN         NaN       NaN   NaN           NaN
7126      NaN         NaN       NaN   NaN           NaN
7127      NaN         NaN       NaN   NaN           NaN
65227     NaN         NaN       NaN   NaN           NaN
79655     NaN         NaN       NaN   NaN           NaN

             In vitro Process in vitro Responder Cell  \
                 Process Type                    Name
7117   Restimulation in vitro                    PBMC
7126   Restimulation in vitro                    PBMC
7127                      NaN                     NaN
65227                     NaN                     NaN
79655                     NaN                     NaN

                                                 in vitro Stimulator Cell  \
                                             IRI                     Name
7117   http://purl.obolibrary.org/obo/CL_2000001                   B cell
7126   http://purl.obolibrary.org/obo/CL_2000001                     PBMC
7127                                         NaN                      NaN
65227                                        NaN                      NaN
79655                                        NaN                      NaN

                                                 in vitro immunogen  \
                                             IRI   Epitope Relation
7117   http://purl.obolibrary.org/obo/CL_0000236            Epitope
7126   http://purl.obolibrary.org/obo/CL_2000001  Taxonomic Sibling
7127                                         NaN                NaN
65227                                        NaN                NaN
79655                                        NaN                NaN

                                                                       \
          Object Type           Name Reference Name Starting Position
7117   Linear peptide      GILGFVFTL            NaN                58
7126          Protein  Hemagglutinin            NaN               NaN
7127              NaN            NaN            NaN               NaN
65227             NaN            NaN            NaN               NaN
79655             NaN            NaN            NaN               NaN

                                                                 \
      Ending Position                                       IRI
7117               66                                       NaN
7126              NaN  https://www.uniprot.org/uniprot/Q8V285.1
7127              NaN                                       NaN
65227             NaN                                       NaN
79655             NaN                                       NaN

                                                                   \
        Source Molecule                       Source Molecule IRI
7117   Matrix protein 1  https://www.uniprot.org/uniprot/P03485.1
7126                NaN                                       NaN
7127                NaN                                       NaN
65227               NaN                                       NaN
79655               NaN                                       NaN

                                                                \
        Molecule Parent                    Molecule Parent IRI
7117   Matrix protein 1  http://www.uniprot.org/uniprot/P03485
7126                NaN                                    NaN
7127                NaN                                    NaN
65227               NaN                                    NaN
79655               NaN                                    NaN

                                                 \
                                Source Organism
7117                          Influenza A virus
7126   Influenza A virus (A/Texas/1/1977(H3N2))
7127                                        NaN

In [19]:
with open("IEDB/1.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df[('Complex', 'PDB ID')].tolist())]))

## 2. PDB drop duplicates

In [20]:
df = df.drop_duplicates(subset=[('Complex', 'PDB ID')])
print(f"IEDB database has: {len(df)} unique PDB")
df.head()

IEDB database has: 304 unique PDB

                                Assay ID  \
                                IEDB IRI
7117   http://www.iedb.org/assay/1005001
7126   http://www.iedb.org/assay/1005014
7127   http://www.iedb.org/assay/1005016
65227  http://www.iedb.org/assay/1404662
79655  http://www.iedb.org/assay/1478873

                                   Reference                        \
                                    IEDB IRI        Type      PMID
7117   http://www.iedb.org/reference/1000291  Literature  12796775
7126   http://www.iedb.org/reference/1000293  Literature  11060013
7127   http://www.iedb.org/reference/1000294  Literature  11877480
65227  http://www.iedb.org/reference/1004650  Literature  12530975
79655  http://www.iedb.org/reference/1008126  Literature   9586631

                     \
      Submission ID
7117            NaN
7126            NaN
7127            NaN
65227           NaN
79655           NaN

                                                                                                            \
                                                                                                   Authors
7117          Guillaume B E Stewart-Jones; Andrew J McMichael; John I Bell; David I Stuart; E Yvonne Jones
7126                                                                        J Hennecke; A Carfi; D C Wiley
7127                                                                            Jens Hennecke; Don C Wiley
65227  Lars Kjer-Nielsen; Craig S Clements; Anthony W Purcell; Andrew G Brooks; James C Whisstock; Scot...
79655                                    Y H Ding; K J Smith; D N Garboczi; U Utz; W E Biddison; D C Wiley

                          \
           Journal  Date
7117   Nat Immunol  2003
7126        EMBO J  2000
7127     J Exp Med  2002
65227     Immunity  2003
79655     Immunity  1998

                                                                                                            \
                                                                                                     Title
7117                              A structural basis for immunodominant human T cell receptor recognition.
7126   Structure of a covalently stabilized complex of a human alphabeta T-cell receptor, influenza HA ...
7127   Structure of a complex of the human alpha/beta T cell receptor (TCR) HA1.7, influenza hemaggluti...
65227   A structural basis for the selection of dominant alphabeta T cell receptors in antiviral immunity.
79655  Two human T cell receptors bind in a similar diagonal mode to the HLA-A2/Tax peptide complex usi...

                                 Epitope                                 \
                                IEDB IRI     Object Type           Name
7117   http://www.iedb.org/epitope/20354  Linear peptide      GILGFVFTL
7126   http://www.iedb.org/epitope/48237  Linear peptide  PKYVKQNTLKLAT
7127   http://www.iedb.org/epitope/48237  Linear peptide  PKYVKQNTLKLAT
65227  http://www.iedb.org/epitope/16878  Linear peptide      FLRGRAYGL
79655  http://www.iedb.org/epitope/37257  Linear peptide      LLFGYPVYV

                                                                            \
                                          Reference Name Modified residues
7117   influenza A virus matrix protein M1 peptide 58-66               NaN
7126             influenza hemagglutinin 306-318 peptide               NaN
7127            influenza haemagglutinin 306-318 peptide               NaN
65227                                       EBNA-3 11-19               NaN
79655                                  Tax peptide 11-19               NaN

                                                                     \
      Modifications Starting Position Ending Position  IRI Synonyms
7117            NaN                58              66  NaN      NaN
7126            NaN               322             334  NaN      NaN
7127            NaN               322             334  NaN      NaN
65227           NaN                11              19  NaN      NaN
79655           NaN                11              19  NaN      NaN

                                      \
                     Source Molecule
7117                Matrix protein 1
7126         Hemagglutinin precursor
7127         Hemagglutinin precursor
65227         nuclear antigen EBNA-3
79655  transcriptional activator Tax

                                                       \
                                  Source Molecule IRI
7117         https://www.uniprot.org/uniprot/P03485.1
7126     http://www.ncbi.nlm.nih.gov/protein/P03437.1
7127     http://www.ncbi.nlm.nih.gov/protein/P03437.1
65227  http://www.ncbi.nlm.nih.gov/protein/AAB20988.1
79655  http://www.ncbi.nlm.nih.gov/protein/AAG31572.1

                                                                              \
                      Molecule Parent                    Molecule Parent IRI
7117                 Matrix protein 1  http://www.uniprot.org/uniprot/P03485
7126                    Hemagglutinin  http://www.uniprot.org/uniprot/P03452
7127                    Hemagglutinin  http://www.uniprot.org/uniprot/P03452
65227  Epstein-Barr nuclear antigen 3  http://www.uniprot.org/uniprot/P12977
79655                   Protein Tax-1  http://www.uniprot.org/uniprot/P14079

                                                 \
                                Source Organism
7117                          Influenza A virus
7126   Influenza A virus (A/Aichi/2/1968(H3N2))
7127   Influenza A virus (A/Aichi/2/1968(H3N2))
65227                  human gammaherpesvirus 4
79655        Human T-cell leukemia virus type I

                                                        \
                                   Source Organism IRI
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320
7126   http://purl.obolibrary.org/obo/NCBITaxon_387139
7127   http://purl.obolibrary.org/obo/NCBITaxon_387139
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376
79655   http://purl.obolibrary.org/obo/NCBITaxon_11908

                                       \
                              Species
7117                Influenza A virus
7126                Influenza A virus
7127                Influenza A virus
65227        human gammaherpesvirus 4
79655  Primate T-lymphotropic virus 1

                                                                         \
                                           Species IRI Epitope Comments
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320              NaN
7126    http://purl.obolibrary.org/obo/NCBITaxon_11320              NaN
7127    http://purl.obolibrary.org/obo/NCBITaxon_11320              NaN
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376              NaN
79655  http://purl.obolibrary.org/obo/NCBITaxon_194440              NaN

        Related Object                                                     \
      Epitope Relation Object Type Name Starting Position Ending Position
7117               NaN         NaN  NaN               NaN             NaN
7126               NaN         NaN  NaN               NaN             NaN
7127               NaN         NaN  NaN               NaN             NaN
65227              NaN         NaN  NaN               NaN             NaN
79655              NaN         NaN  NaN               NaN             NaN

                                                                         \
       IRI Synonyms Source Molecule Source Molecule IRI Molecule Parent
7117   NaN      NaN             NaN                 NaN             NaN
7126   NaN      NaN             NaN                 NaN             NaN
7127   NaN      NaN             NaN                 NaN             NaN
65227  NaN      NaN             NaN                 NaN             NaN
79655  NaN      NaN             NaN                 NaN             NaN

                                                                       \
      Molecule Parent IRI Source Organism Source Organism IRI Species
7117                  NaN             NaN                 NaN     NaN
7126                  NaN             NaN                 NaN     NaN
7127                  NaN             NaN                 NaN     NaN
65227                 NaN             NaN                 NaN     NaN
79655                 NaN             NaN                 NaN     NaN

                                   Host  \
      Species IRI                  Name
7117          NaN  Homo sapiens (human)
7126          NaN  Homo sapiens (human)
7127          NaN  Homo sapiens (human)
65227         NaN  Homo sapiens (human)
79655         NaN  Homo sapiens (human)

                                                                  \
                                                 IRI Geolocation
7117   http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
7126   http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
7127   http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
65227  http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
79655  http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN

                                             \
      Geolocation IRI  Sex  Age MHC Present
7117              NaN  NaN  NaN         NaN
7126              NaN  NaN  NaN         NaN
7127              NaN  NaN  NaN         NaN
65227             NaN  NaN  NaN         NaN
79655             NaN  NaN  NaN         NaN

                                                                   1st in vivo Process  \
                                                                          Process Type
7117   Environmental exposure to endemic/ubiquitous agent without evidence for disease
7126             Exposure with existing immune reactivity without evidence for disease
7127                                                                           Unknown
65227  Environmental exposure to endemic/ubiquitous agent without evidence for disease
79655                                                 Occurrence of infectious disease

                                                                              \
                            Disease                              Disease IRI
7117                            NaN                                      NaN
7126                            NaN                                      NaN
7127                            NaN                                      NaN
65227                           NaN                                      NaN
79655  tropical spastic paraparesis  http://purl.obolibrary.org/obo/DOID_321

                         1st immunogen              \
      Disease Stage   Epitope Relation Object Type
7117            NaN    Source Organism    Organism
7126            NaN  Taxonomic Sibling    Organism
7127            NaN                NaN         NaN
65227           NaN    Source Organism    Organism
79655       Chronic    Source Organism    Organism

                                                                                           \
                                                                                     Name
7117                                                                    Influenza A virus
7126   Influenza A virus (A/Texas/1/1977(H3N2)) (Influenza A virus (A/Texas/1/77 (H3N2)))
7127                                                                                  NaN
65227                                            Human herpesvirus 4 (Epstein Barr virus)
79655             Human T-cell leukemia virus type I (Human T cell leukemia virus type 1)

                                                                   \
            Reference Name Starting Position Ending Position  IRI
7117                   NaN               NaN             NaN  NaN
7126                   NaN               NaN             NaN  NaN
7127                   NaN               NaN             NaN  NaN
65227  Human herpesvirus 4               NaN             NaN  NaN
79655                  NaN               NaN             NaN  NaN

                                                                               \
      Source Molecule Source Molecule IRI Molecule Parent Molecule Parent IRI
7117              NaN                 NaN             NaN                 NaN
7126              NaN                 NaN             NaN                 NaN
7127              NaN                 NaN             NaN                 NaN
65227             NaN                 NaN             NaN                 NaN
79655             NaN                 NaN             NaN                 NaN

                                                 \
                                Source Organism
7117                          Influenza A virus
7126   Influenza A virus (A/Texas/1/1977(H3N2))
7127                                        NaN
65227                  human gammaherpesvirus 4
79655        Human T-cell leukemia virus type I

                                                        \
                                   Source Organism IRI
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320
7126   http://purl.obolibrary.org/obo/NCBITaxon_444318
7127                                               NaN
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376
79655   http://purl.obolibrary.org/obo/NCBITaxon_11908

                                       \
                              Species
7117                Influenza A virus
7126                Influenza A virus
7127                              NaN
65227        human gammaherpesvirus 4
79655  Primate T-lymphotropic virus 1

                                                                        \
                                           Species IRI Adjuvants Route
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320       NaN   NaN
7126    http://purl.obolibrary.org/obo/NCBITaxon_11320       NaN   NaN
7127                                               NaN       NaN   NaN
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376       NaN   NaN
79655  http://purl.obolibrary.org/obo/NCBITaxon_194440       NaN   NaN

                    2nd in vivo Process                                    \
      Dose Schedule        Process Type Disease Disease IRI Disease Stage
7117            NaN                 NaN     NaN         NaN           NaN
7126            NaN                 NaN     NaN         NaN           NaN
7127            NaN                 NaN     NaN         NaN           NaN
65227           NaN                 NaN     NaN         NaN           NaN
79655           NaN                 NaN     NaN         NaN           NaN

         2nd immunogen                                                    \
      Epitope Relation Object Type Name Reference Name Starting Position
7117               NaN         NaN  NaN            NaN               NaN
7126               NaN         NaN  NaN            NaN               NaN
7127               NaN         NaN  NaN            NaN               NaN
65227              NaN         NaN  NaN            NaN               NaN
79655              NaN         NaN  NaN            NaN               NaN

                                                                \
      Ending Position  IRI Source Molecule Source Molecule IRI
7117              NaN  NaN             NaN                 NaN
7126              NaN  NaN             NaN                 NaN
7127              NaN  NaN             NaN                 NaN
65227             NaN  NaN             NaN                 NaN
79655             NaN  NaN             NaN                 NaN

                                                                               \
      Molecule Parent Molecule Parent IRI Source Organism Source Organism IRI
7117              NaN                 NaN             NaN                 NaN
7126              NaN                 NaN             NaN                 NaN
7127              NaN                 NaN             NaN                 NaN
65227             NaN                 NaN             NaN                 NaN
79655             NaN                 NaN             NaN                 NaN

                                                         \
      Species Species IRI Adjuvants Route Dose Schedule
7117      NaN         NaN       NaN   NaN           NaN
7126      NaN         NaN       NaN   NaN           NaN
7127      NaN         NaN       NaN   NaN           NaN
65227     NaN         NaN       NaN   NaN           NaN
79655     NaN         NaN       NaN   NaN           NaN

             In vitro Process in vitro Responder Cell  \
                 Process Type                    Name
7117   Restimulation in vitro                    PBMC
7126   Restimulation in vitro                    PBMC
7127                      NaN                     NaN
65227                     NaN                     NaN
79655                     NaN                     NaN

                                                 in vitro Stimulator Cell  \
                                             IRI                     Name
7117   http://purl.obolibrary.org/obo/CL_2000001                   B cell
7126   http://purl.obolibrary.org/obo/CL_2000001                     PBMC
7127                                         NaN                      NaN
65227                                        NaN                      NaN
79655                                        NaN                      NaN

                                                 in vitro immunogen  \
                                             IRI   Epitope Relation
7117   http://purl.obolibrary.org/obo/CL_0000236            Epitope
7126   http://purl.obolibrary.org/obo/CL_2000001  Taxonomic Sibling
7127                                         NaN                NaN
65227                                        NaN                NaN
79655                                        NaN                NaN

                                                                       \
          Object Type           Name Reference Name Starting Position
7117   Linear peptide      GILGFVFTL            NaN                58
7126          Protein  Hemagglutinin            NaN               NaN
7127              NaN            NaN            NaN               NaN
65227             NaN            NaN            NaN               NaN
79655             NaN            NaN            NaN               NaN

                                                                 \
      Ending Position                                       IRI
7117               66                                       NaN
7126              NaN  https://www.uniprot.org/uniprot/Q8V285.1
7127              NaN                                       NaN
65227             NaN                                       NaN
79655             NaN                                       NaN

                                                                   \
        Source Molecule                       Source Molecule IRI
7117   Matrix protein 1  https://www.uniprot.org/uniprot/P03485.1
7126                NaN                                       NaN
7127                NaN                                       NaN
65227               NaN                                       NaN
79655               NaN                                       NaN

                                                                \
        Molecule Parent                    Molecule Parent IRI
7117   Matrix protein 1  http://www.uniprot.org/uniprot/P03485
7126                NaN                                    NaN
7127                NaN                                    NaN
65227               NaN                                    NaN
79655               NaN                                    NaN

                                                 \
                                Source Organism
7117                          Influenza A virus
7126   Influenza A virus (A/Texas/1/1977(H3N2))
7127                                        NaN

In [21]:
with open("IEDB/2.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df[('Complex', 'PDB ID')].tolist())]))

## 3. Keep human MHC

In [22]:
df = df.loc[df[('MHC Restriction', 'Name')].str.upper().str[:3]=='HLA']
print(f"ATLAS database has: {len(df)} unique human PDB")
df.head()

ATLAS database has: 241 unique human PDB

                                Assay ID  \
                                IEDB IRI
7117   http://www.iedb.org/assay/1005001
7126   http://www.iedb.org/assay/1005014
7127   http://www.iedb.org/assay/1005016
65227  http://www.iedb.org/assay/1404662
79655  http://www.iedb.org/assay/1478873

                                   Reference                        \
                                    IEDB IRI        Type      PMID
7117   http://www.iedb.org/reference/1000291  Literature  12796775
7126   http://www.iedb.org/reference/1000293  Literature  11060013
7127   http://www.iedb.org/reference/1000294  Literature  11877480
65227  http://www.iedb.org/reference/1004650  Literature  12530975
79655  http://www.iedb.org/reference/1008126  Literature   9586631

                     \
      Submission ID
7117            NaN
7126            NaN
7127            NaN
65227           NaN
79655           NaN

                                                                                                            \
                                                                                                   Authors
7117          Guillaume B E Stewart-Jones; Andrew J McMichael; John I Bell; David I Stuart; E Yvonne Jones
7126                                                                        J Hennecke; A Carfi; D C Wiley
7127                                                                            Jens Hennecke; Don C Wiley
65227  Lars Kjer-Nielsen; Craig S Clements; Anthony W Purcell; Andrew G Brooks; James C Whisstock; Scot...
79655                                    Y H Ding; K J Smith; D N Garboczi; U Utz; W E Biddison; D C Wiley

                          \
           Journal  Date
7117   Nat Immunol  2003
7126        EMBO J  2000
7127     J Exp Med  2002
65227     Immunity  2003
79655     Immunity  1998

                                                                                                            \
                                                                                                     Title
7117                              A structural basis for immunodominant human T cell receptor recognition.
7126   Structure of a covalently stabilized complex of a human alphabeta T-cell receptor, influenza HA ...
7127   Structure of a complex of the human alpha/beta T cell receptor (TCR) HA1.7, influenza hemaggluti...
65227   A structural basis for the selection of dominant alphabeta T cell receptors in antiviral immunity.
79655  Two human T cell receptors bind in a similar diagonal mode to the HLA-A2/Tax peptide complex usi...

                                 Epitope                                 \
                                IEDB IRI     Object Type           Name
7117   http://www.iedb.org/epitope/20354  Linear peptide      GILGFVFTL
7126   http://www.iedb.org/epitope/48237  Linear peptide  PKYVKQNTLKLAT
7127   http://www.iedb.org/epitope/48237  Linear peptide  PKYVKQNTLKLAT
65227  http://www.iedb.org/epitope/16878  Linear peptide      FLRGRAYGL
79655  http://www.iedb.org/epitope/37257  Linear peptide      LLFGYPVYV

                                                                            \
                                          Reference Name Modified residues
7117   influenza A virus matrix protein M1 peptide 58-66               NaN
7126             influenza hemagglutinin 306-318 peptide               NaN
7127            influenza haemagglutinin 306-318 peptide               NaN
65227                                       EBNA-3 11-19               NaN
79655                                  Tax peptide 11-19               NaN

                                                                     \
      Modifications Starting Position Ending Position  IRI Synonyms
7117            NaN                58              66  NaN      NaN
7126            NaN               322             334  NaN      NaN
7127            NaN               322             334  NaN      NaN
65227           NaN                11              19  NaN      NaN
79655           NaN                11              19  NaN      NaN

                                      \
                     Source Molecule
7117                Matrix protein 1
7126         Hemagglutinin precursor
7127         Hemagglutinin precursor
65227         nuclear antigen EBNA-3
79655  transcriptional activator Tax

                                                       \
                                  Source Molecule IRI
7117         https://www.uniprot.org/uniprot/P03485.1
7126     http://www.ncbi.nlm.nih.gov/protein/P03437.1
7127     http://www.ncbi.nlm.nih.gov/protein/P03437.1
65227  http://www.ncbi.nlm.nih.gov/protein/AAB20988.1
79655  http://www.ncbi.nlm.nih.gov/protein/AAG31572.1

                                                                              \
                      Molecule Parent                    Molecule Parent IRI
7117                 Matrix protein 1  http://www.uniprot.org/uniprot/P03485
7126                    Hemagglutinin  http://www.uniprot.org/uniprot/P03452
7127                    Hemagglutinin  http://www.uniprot.org/uniprot/P03452
65227  Epstein-Barr nuclear antigen 3  http://www.uniprot.org/uniprot/P12977
79655                   Protein Tax-1  http://www.uniprot.org/uniprot/P14079

                                                 \
                                Source Organism
7117                          Influenza A virus
7126   Influenza A virus (A/Aichi/2/1968(H3N2))
7127   Influenza A virus (A/Aichi/2/1968(H3N2))
65227                  human gammaherpesvirus 4
79655        Human T-cell leukemia virus type I

                                                        \
                                   Source Organism IRI
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320
7126   http://purl.obolibrary.org/obo/NCBITaxon_387139
7127   http://purl.obolibrary.org/obo/NCBITaxon_387139
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376
79655   http://purl.obolibrary.org/obo/NCBITaxon_11908

                                       \
                              Species
7117                Influenza A virus
7126                Influenza A virus
7127                Influenza A virus
65227        human gammaherpesvirus 4
79655  Primate T-lymphotropic virus 1

                                                                         \
                                           Species IRI Epitope Comments
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320              NaN
7126    http://purl.obolibrary.org/obo/NCBITaxon_11320              NaN
7127    http://purl.obolibrary.org/obo/NCBITaxon_11320              NaN
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376              NaN
79655  http://purl.obolibrary.org/obo/NCBITaxon_194440              NaN

        Related Object                                                     \
      Epitope Relation Object Type Name Starting Position Ending Position
7117               NaN         NaN  NaN               NaN             NaN
7126               NaN         NaN  NaN               NaN             NaN
7127               NaN         NaN  NaN               NaN             NaN
65227              NaN         NaN  NaN               NaN             NaN
79655              NaN         NaN  NaN               NaN             NaN

                                                                         \
       IRI Synonyms Source Molecule Source Molecule IRI Molecule Parent
7117   NaN      NaN             NaN                 NaN             NaN
7126   NaN      NaN             NaN                 NaN             NaN
7127   NaN      NaN             NaN                 NaN             NaN
65227  NaN      NaN             NaN                 NaN             NaN
79655  NaN      NaN             NaN                 NaN             NaN

                                                                       \
      Molecule Parent IRI Source Organism Source Organism IRI Species
7117                  NaN             NaN                 NaN     NaN
7126                  NaN             NaN                 NaN     NaN
7127                  NaN             NaN                 NaN     NaN
65227                 NaN             NaN                 NaN     NaN
79655                 NaN             NaN                 NaN     NaN

                                   Host  \
      Species IRI                  Name
7117          NaN  Homo sapiens (human)
7126          NaN  Homo sapiens (human)
7127          NaN  Homo sapiens (human)
65227         NaN  Homo sapiens (human)
79655         NaN  Homo sapiens (human)

                                                                  \
                                                 IRI Geolocation
7117   http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
7126   http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
7127   http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
65227  http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN
79655  http://purl.obolibrary.org/obo/NCBITaxon_9606         NaN

                                             \
      Geolocation IRI  Sex  Age MHC Present
7117              NaN  NaN  NaN         NaN
7126              NaN  NaN  NaN         NaN
7127              NaN  NaN  NaN         NaN
65227             NaN  NaN  NaN         NaN
79655             NaN  NaN  NaN         NaN

                                                                   1st in vivo Process  \
                                                                          Process Type
7117   Environmental exposure to endemic/ubiquitous agent without evidence for disease
7126             Exposure with existing immune reactivity without evidence for disease
7127                                                                           Unknown
65227  Environmental exposure to endemic/ubiquitous agent without evidence for disease
79655                                                 Occurrence of infectious disease

                                                                              \
                            Disease                              Disease IRI
7117                            NaN                                      NaN
7126                            NaN                                      NaN
7127                            NaN                                      NaN
65227                           NaN                                      NaN
79655  tropical spastic paraparesis  http://purl.obolibrary.org/obo/DOID_321

                         1st immunogen              \
      Disease Stage   Epitope Relation Object Type
7117            NaN    Source Organism    Organism
7126            NaN  Taxonomic Sibling    Organism
7127            NaN                NaN         NaN
65227           NaN    Source Organism    Organism
79655       Chronic    Source Organism    Organism

                                                                                           \
                                                                                     Name
7117                                                                    Influenza A virus
7126   Influenza A virus (A/Texas/1/1977(H3N2)) (Influenza A virus (A/Texas/1/77 (H3N2)))
7127                                                                                  NaN
65227                                            Human herpesvirus 4 (Epstein Barr virus)
79655             Human T-cell leukemia virus type I (Human T cell leukemia virus type 1)

                                                                   \
            Reference Name Starting Position Ending Position  IRI
7117                   NaN               NaN             NaN  NaN
7126                   NaN               NaN             NaN  NaN
7127                   NaN               NaN             NaN  NaN
65227  Human herpesvirus 4               NaN             NaN  NaN
79655                  NaN               NaN             NaN  NaN

                                                                               \
      Source Molecule Source Molecule IRI Molecule Parent Molecule Parent IRI
7117              NaN                 NaN             NaN                 NaN
7126              NaN                 NaN             NaN                 NaN
7127              NaN                 NaN             NaN                 NaN
65227             NaN                 NaN             NaN                 NaN
79655             NaN                 NaN             NaN                 NaN

                                                 \
                                Source Organism
7117                          Influenza A virus
7126   Influenza A virus (A/Texas/1/1977(H3N2))
7127                                        NaN
65227                  human gammaherpesvirus 4
79655        Human T-cell leukemia virus type I

                                                        \
                                   Source Organism IRI
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320
7126   http://purl.obolibrary.org/obo/NCBITaxon_444318
7127                                               NaN
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376
79655   http://purl.obolibrary.org/obo/NCBITaxon_11908

                                       \
                              Species
7117                Influenza A virus
7126                Influenza A virus
7127                              NaN
65227        human gammaherpesvirus 4
79655  Primate T-lymphotropic virus 1

                                                                        \
                                           Species IRI Adjuvants Route
7117    http://purl.obolibrary.org/obo/NCBITaxon_11320       NaN   NaN
7126    http://purl.obolibrary.org/obo/NCBITaxon_11320       NaN   NaN
7127                                               NaN       NaN   NaN
65227   http://purl.obolibrary.org/obo/NCBITaxon_10376       NaN   NaN
79655  http://purl.obolibrary.org/obo/NCBITaxon_194440       NaN   NaN

                    2nd in vivo Process                                    \
      Dose Schedule        Process Type Disease Disease IRI Disease Stage
7117            NaN                 NaN     NaN         NaN           NaN
7126            NaN                 NaN     NaN         NaN           NaN
7127            NaN                 NaN     NaN         NaN           NaN
65227           NaN                 NaN     NaN         NaN           NaN
79655           NaN                 NaN     NaN         NaN           NaN

         2nd immunogen                                                    \
      Epitope Relation Object Type Name Reference Name Starting Position
7117               NaN         NaN  NaN            NaN               NaN
7126               NaN         NaN  NaN            NaN               NaN
7127               NaN         NaN  NaN            NaN               NaN
65227              NaN         NaN  NaN            NaN               NaN
79655              NaN         NaN  NaN            NaN               NaN

                                                                \
      Ending Position  IRI Source Molecule Source Molecule IRI
7117              NaN  NaN             NaN                 NaN
7126              NaN  NaN             NaN                 NaN
7127              NaN  NaN             NaN                 NaN
65227             NaN  NaN             NaN                 NaN
79655             NaN  NaN             NaN                 NaN

                                                                               \
      Molecule Parent Molecule Parent IRI Source Organism Source Organism IRI
7117              NaN                 NaN             NaN                 NaN
7126              NaN                 NaN             NaN                 NaN
7127              NaN                 NaN             NaN                 NaN
65227             NaN                 NaN             NaN                 NaN
79655             NaN                 NaN             NaN                 NaN

                                                         \
      Species Species IRI Adjuvants Route Dose Schedule
7117      NaN         NaN       NaN   NaN           NaN
7126      NaN         NaN       NaN   NaN           NaN
7127      NaN         NaN       NaN   NaN           NaN
65227     NaN         NaN       NaN   NaN           NaN
79655     NaN         NaN       NaN   NaN           NaN

             In vitro Process in vitro Responder Cell  \
                 Process Type                    Name
7117   Restimulation in vitro                    PBMC
7126   Restimulation in vitro                    PBMC
7127                      NaN                     NaN
65227                     NaN                     NaN
79655                     NaN                     NaN

                                                 in vitro Stimulator Cell  \
                                             IRI                     Name
7117   http://purl.obolibrary.org/obo/CL_2000001                   B cell
7126   http://purl.obolibrary.org/obo/CL_2000001                     PBMC
7127                                         NaN                      NaN
65227                                        NaN                      NaN
79655                                        NaN                      NaN

                                                 in vitro immunogen  \
                                             IRI   Epitope Relation
7117   http://purl.obolibrary.org/obo/CL_0000236            Epitope
7126   http://purl.obolibrary.org/obo/CL_2000001  Taxonomic Sibling
7127                                         NaN                NaN
65227                                        NaN                NaN
79655                                        NaN                NaN

                                                                       \
          Object Type           Name Reference Name Starting Position
7117   Linear peptide      GILGFVFTL            NaN                58
7126          Protein  Hemagglutinin            NaN               NaN
7127              NaN            NaN            NaN               NaN
65227             NaN            NaN            NaN               NaN
79655             NaN            NaN            NaN               NaN

                                                                 \
      Ending Position                                       IRI
7117               66                                       NaN
7126              NaN  https://www.uniprot.org/uniprot/Q8V285.1
7127              NaN                                       NaN
65227             NaN                                       NaN
79655             NaN                                       NaN

                                                                   \
        Source Molecule                       Source Molecule IRI
7117   Matrix protein 1  https://www.uniprot.org/uniprot/P03485.1
7126                NaN                                       NaN
7127                NaN                                       NaN
65227               NaN                                       NaN
79655               NaN                                       NaN

                                                                \
        Molecule Parent                    Molecule Parent IRI
7117   Matrix protein 1  http://www.uniprot.org/uniprot/P03485
7126                NaN                                    NaN
7127                NaN                                    NaN
65227               NaN                                    NaN
79655               NaN                                    NaN

                                                 \
                                Source Organism
7117                          Influenza A virus
7126   Influenza A virus (A/Texas/1/1977(H3N2))
7127                                        NaN

In [23]:
df[('Complex', 'PDB ID')].rename('IEDB').to_csv('IEDB/IEDB_pdb.csv', index=False)

In [24]:
with open("IEDB/3.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df[('Complex', 'PDB ID')].tolist())]))

In [36]:
df[[('Complex', 'PDB ID'), ('MHC Restriction', 'Name')]].rename(columns={('Complex', 'PDB ID'):'pdb', ('MHC Restriction', 'Name'):'IEDB_mhc'}).to_csv('IEDB/IEDB_hla.csv', index=False)