In [17]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('max_colwidth', 100)

In [18]:
# !mkdir STCRDab
# !wget https://opig.stats.ox.ac.uk/webapps/stcrdab-stcrpred/summary/all -O STCRDab/STCRDab_raw.tsv

In [19]:
df = pd.read_csv("STCRDab/STCRDab_raw.tsv", sep='\t', dtype=object)
print(f"STCRDab database has {len(df)} records has TCR structures")
df.head()

STCRDab database has 984 records has TCR structures

,pdb,Bchain,Achain,Dchain,Gchain,TCRtype,model,antigen_chain,antigen_type,antigen_name,antigen_het_name,mhc_type,mhc_chain1,mhc_chain2,docking_angle,beta_subgroup,alpha_subgroup,gamma_subgroup,delta_subgroup,short_header,date,compound,beta_organism,alpha_organism,gamma_organism,delta_organism,antigen_organism,mhc_chain1_organism,mhc_chain2_organism,authors,resolution,method,r_free,r_factor,affinity,affinity_method,affinity_temperature,affinity_pmid,engineered
0,8trq,E,D,NaN,NaN,abTCR,0,C,peptide,vimentin,NaN,GB,B,NaN,NaN,TRBV19,TRAV6,NaN,NaN,IMMUNE SYSTEM,07/31/24,T cell recognition of citrullinated vimentin peptide presented by HLA-DR4,mus musculus,mus musculus,NaN,NaN,homo sapiens,homo sapiens,NaN,"Loh, T.J., Lim, J.J., Reid, H.H., Rossjohn, J.",2.75,X-RAY DIFFRACTION,0.264,0.216,NaN,NaN,NaN,NaN,True
1,3qux,D,C,NaN,NaN,abTCR,0,A,Hapten,"N-[(3S,4S,5R)-4,5-DIHYDROXY-1-[(2R,3R,4R,5R,6R)-3,4,5-TRIHYDROXY-6-(HYDROXYMETHYL)OXAN-2-YL]NONA...",QUX,CD1,A,B,25.713,TRBV13,TRAV11,NaN,NaN,IMMUNE SYSTEM,06/29/11,Structure of the mouse CD1d-alpha-C-GalCer-iNKT TCR complex,mus musculus,mus musculus,NaN,NaN,mus musculus,mus musculus,mus musculus,"Li, Y., Girardi, E., Yu, E.D., Zajonc, D.M.",2.91,X-RAY DIFFRACTION,0.252,0.208,NaN,NaN,NaN,NaN,True
2,4ozi,H,G,NaN,NaN,abTCR,0,J,peptide,deamidated gliadin-alpha1 peptide,NaN,MH2,A,B,45.767,TRBV20,TRAV4,NaN,NaN,IMMUNE SYSTEM,04/16/14,S2 protein complex,homo sapiens,homo sapiens,NaN,NaN,triticum aestivum,homo sapiens,homo sapiens,"Petersen, J., Reid, H.H., Rossjohn, J.",3.2,X-RAY DIFFRACTION,0.243,0.213,NaN,NaN,NaN,NaN,True
3,2ak4,E,D,NaN,NaN,abTCR,0,C,peptide,ebv peptide lpeplpqgqltay,NaN,MH1,A,B,71.108,TRBV6,TRAV19,NaN,NaN,IMMUNE SYSTEM,10/11/05,Crystal Structure of SB27 TCR in complex with HLA-B*3508-13mer peptide,homo sapiens,homo sapiens,NaN,NaN,NaN,homo sapiens,homo sapiens,"Tynan, F.E., Burrows, S.R., Buckle, A.M., Clements, C.S., Borg, N.A., Miles, J.J., Beddoe, T., W...",2.5,X-RAY DIFFRACTION,0.278,0.246,NaN,NaN,NaN,NaN,True
4,2aq3,G,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRBV13,NaN,NaN,NaN,IMMUNE SYSTEM,03/21/06,Crystal structure of T-cell receptor V beta domain variant complexed with superantigen SEC3,mus musculus,NaN,NaN,NaN,NaN,NaN,NaN,"Cho, S., Swaminathan, C.P., Yang, J., Kerzic, M.C., Guan, R., Kieke, M.C., Kranz, D.M., Mariuzza...",2.3,X-RAY DIFFRACTION,0.271,0.206,NaN,NaN,NaN,NaN,True

In [20]:
with open("STCRDab/0.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['pdb'].tolist())]))

## 1. Using rules to filter out pdb records

1. TCRtype = 'abTCR'
2. antigen_type = 'peptide'
3. mhc_type = 'MH1/MH2'

In [21]:
df = df.loc[(df['TCRtype']=='abTCR') & (df['antigen_type']=='peptide') & df['mhc_type'].isin(['MH1','MH2'])] 
df['pdb'] = df['pdb'].str.lower()

print(f"STCRDab database has {len(df)} rows matched rules")
df.head()

STCRDab database has 446 rows matched rules

,pdb,Bchain,Achain,Dchain,Gchain,TCRtype,model,antigen_chain,antigen_type,antigen_name,antigen_het_name,mhc_type,mhc_chain1,mhc_chain2,docking_angle,beta_subgroup,alpha_subgroup,gamma_subgroup,delta_subgroup,short_header,date,compound,beta_organism,alpha_organism,gamma_organism,delta_organism,antigen_organism,mhc_chain1_organism,mhc_chain2_organism,authors,resolution,method,r_free,r_factor,affinity,affinity_method,affinity_temperature,affinity_pmid,engineered
2,4ozi,H,G,NaN,NaN,abTCR,0,J,peptide,deamidated gliadin-alpha1 peptide,NaN,MH2,A,B,45.767,TRBV20,TRAV4,NaN,NaN,IMMUNE SYSTEM,04/16/14,S2 protein complex,homo sapiens,homo sapiens,NaN,NaN,triticum aestivum,homo sapiens,homo sapiens,"Petersen, J., Reid, H.H., Rossjohn, J.",3.2,X-RAY DIFFRACTION,0.243,0.213,NaN,NaN,NaN,NaN,True
3,2ak4,E,D,NaN,NaN,abTCR,0,C,peptide,ebv peptide lpeplpqgqltay,NaN,MH1,A,B,71.108,TRBV6,TRAV19,NaN,NaN,IMMUNE SYSTEM,10/11/05,Crystal Structure of SB27 TCR in complex with HLA-B*3508-13mer peptide,homo sapiens,homo sapiens,NaN,NaN,NaN,homo sapiens,homo sapiens,"Tynan, F.E., Burrows, S.R., Buckle, A.M., Clements, C.S., Borg, N.A., Miles, J.J., Beddoe, T., W...",2.5,X-RAY DIFFRACTION,0.278,0.246,NaN,NaN,NaN,NaN,True
5,5eu6,E,D,NaN,NaN,abTCR,0,C,peptide,tyr-leu-glu-pro-gly-pro-val-thr-val,NaN,MH1,A,B,47.784,TRBV7,TRAV21,NaN,NaN,IMMUNE SYSTEM,03/02/16,HLA Class I antigen,homo sapiens,homo sapiens,NaN,NaN,synthetic construct,homo sapiens,homo sapiens,"Rizkallah, P.J., Bianchi, V., Cole, D.K., Sewell, A.K.",2.02,X-RAY DIFFRACTION,0.222,0.181,NaN,NaN,NaN,NaN,True
7,7pbe,J,I,NaN,NaN,abTCR,0,H,peptide,spike protein s1,NaN,MH1,F,G,49.843,TRBV7,TRAV12,NaN,NaN,IMMUNE SYSTEM,04/27/22,Emergence of immune escape at dominant SARS-CoV-2 killer T-cell epitope,homo sapiens,homo sapiens,NaN,NaN,severe acute respiratory syndrome coronavirus2,homo sapiens,homo sapiens,"Rizkallah, P.J., Sewell, A.K., Wall, A., Fuller, A.",3,X-RAY DIFFRACTION,0.296,0.228,NaN,NaN,NaN,NaN,True
9,6v18,E,D,NaN,NaN,abTCR,0,C,peptide,fibrinogen beta,NaN,MH2,A,B,23.340,TRBV4,TRAV6,NaN,NaN,IMMUNE SYSTEM,11/25/20,immune receptor complex,mus musculus,mus musculus,NaN,NaN,homo sapiens,homo sapiens,homo sapiens,"Lim, J.J., Rossjohn, J.",2.35,X-RAY DIFFRACTION,0.231,0.193,NaN,NaN,NaN,NaN,True

In [22]:
with open("STCRDab/1.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['pdb'].tolist())]))

## 2. PDB drop duplicates

In [23]:
df = df.drop_duplicates(subset=['pdb'])
print(f"STCRDab database has: {len(df)} unique PDB")
df.head()

STCRDab database has: 279 unique PDB

,pdb,Bchain,Achain,Dchain,Gchain,TCRtype,model,antigen_chain,antigen_type,antigen_name,antigen_het_name,mhc_type,mhc_chain1,mhc_chain2,docking_angle,beta_subgroup,alpha_subgroup,gamma_subgroup,delta_subgroup,short_header,date,compound,beta_organism,alpha_organism,gamma_organism,delta_organism,antigen_organism,mhc_chain1_organism,mhc_chain2_organism,authors,resolution,method,r_free,r_factor,affinity,affinity_method,affinity_temperature,affinity_pmid,engineered
2,4ozi,H,G,NaN,NaN,abTCR,0,J,peptide,deamidated gliadin-alpha1 peptide,NaN,MH2,A,B,45.767,TRBV20,TRAV4,NaN,NaN,IMMUNE SYSTEM,04/16/14,S2 protein complex,homo sapiens,homo sapiens,NaN,NaN,triticum aestivum,homo sapiens,homo sapiens,"Petersen, J., Reid, H.H., Rossjohn, J.",3.2,X-RAY DIFFRACTION,0.243,0.213,NaN,NaN,NaN,NaN,True
3,2ak4,E,D,NaN,NaN,abTCR,0,C,peptide,ebv peptide lpeplpqgqltay,NaN,MH1,A,B,71.108,TRBV6,TRAV19,NaN,NaN,IMMUNE SYSTEM,10/11/05,Crystal Structure of SB27 TCR in complex with HLA-B*3508-13mer peptide,homo sapiens,homo sapiens,NaN,NaN,NaN,homo sapiens,homo sapiens,"Tynan, F.E., Burrows, S.R., Buckle, A.M., Clements, C.S., Borg, N.A., Miles, J.J., Beddoe, T., W...",2.5,X-RAY DIFFRACTION,0.278,0.246,NaN,NaN,NaN,NaN,True
5,5eu6,E,D,NaN,NaN,abTCR,0,C,peptide,tyr-leu-glu-pro-gly-pro-val-thr-val,NaN,MH1,A,B,47.784,TRBV7,TRAV21,NaN,NaN,IMMUNE SYSTEM,03/02/16,HLA Class I antigen,homo sapiens,homo sapiens,NaN,NaN,synthetic construct,homo sapiens,homo sapiens,"Rizkallah, P.J., Bianchi, V., Cole, D.K., Sewell, A.K.",2.02,X-RAY DIFFRACTION,0.222,0.181,NaN,NaN,NaN,NaN,True
7,7pbe,J,I,NaN,NaN,abTCR,0,H,peptide,spike protein s1,NaN,MH1,F,G,49.843,TRBV7,TRAV12,NaN,NaN,IMMUNE SYSTEM,04/27/22,Emergence of immune escape at dominant SARS-CoV-2 killer T-cell epitope,homo sapiens,homo sapiens,NaN,NaN,severe acute respiratory syndrome coronavirus2,homo sapiens,homo sapiens,"Rizkallah, P.J., Sewell, A.K., Wall, A., Fuller, A.",3,X-RAY DIFFRACTION,0.296,0.228,NaN,NaN,NaN,NaN,True
9,6v18,E,D,NaN,NaN,abTCR,0,C,peptide,fibrinogen beta,NaN,MH2,A,B,23.340,TRBV4,TRAV6,NaN,NaN,IMMUNE SYSTEM,11/25/20,immune receptor complex,mus musculus,mus musculus,NaN,NaN,homo sapiens,homo sapiens,homo sapiens,"Lim, J.J., Rossjohn, J.",2.35,X-RAY DIFFRACTION,0.231,0.193,NaN,NaN,NaN,NaN,True

In [24]:
with open("STCRDab/2.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['pdb'].tolist())]))

## 3. Select HLA

In [25]:
df = df.loc[df['compound'].str.upper().str.contains('HLA')]
print(f"STCRDab database has: {len(df)} unique human PDB")
df.head()

STCRDab database has: 158 unique human PDB

,pdb,Bchain,Achain,Dchain,Gchain,TCRtype,model,antigen_chain,antigen_type,antigen_name,antigen_het_name,mhc_type,mhc_chain1,mhc_chain2,docking_angle,beta_subgroup,alpha_subgroup,gamma_subgroup,delta_subgroup,short_header,date,compound,beta_organism,alpha_organism,gamma_organism,delta_organism,antigen_organism,mhc_chain1_organism,mhc_chain2_organism,authors,resolution,method,r_free,r_factor,affinity,affinity_method,affinity_temperature,affinity_pmid,engineered
3,2ak4,E,D,NaN,NaN,abTCR,0,C,peptide,ebv peptide lpeplpqgqltay,NaN,MH1,A,B,71.108,TRBV6,TRAV19,NaN,NaN,IMMUNE SYSTEM,10/11/05,Crystal Structure of SB27 TCR in complex with HLA-B*3508-13mer peptide,homo sapiens,homo sapiens,NaN,NaN,NaN,homo sapiens,homo sapiens,"Tynan, F.E., Burrows, S.R., Buckle, A.M., Clements, C.S., Borg, N.A., Miles, J.J., Beddoe, T., W...",2.5,X-RAY DIFFRACTION,0.278,0.246,NaN,NaN,NaN,NaN,True
5,5eu6,E,D,NaN,NaN,abTCR,0,C,peptide,tyr-leu-glu-pro-gly-pro-val-thr-val,NaN,MH1,A,B,47.784,TRBV7,TRAV21,NaN,NaN,IMMUNE SYSTEM,03/02/16,HLA Class I antigen,homo sapiens,homo sapiens,NaN,NaN,synthetic construct,homo sapiens,homo sapiens,"Rizkallah, P.J., Bianchi, V., Cole, D.K., Sewell, A.K.",2.02,X-RAY DIFFRACTION,0.222,0.181,NaN,NaN,NaN,NaN,True
10,8eo8,E,D,NaN,NaN,abTCR,0,C,peptide,nucleoprotein np8 epitope,NaN,MH1,A,B,41.527,TRBV20,TRAV13,NaN,NaN,IMMUNE SYSTEM,03/27/24,Cross-reactive 3180 TCR recognition of HLA-B*35:01-NP8 epitope from 2005 H1N1 influenza strain,homo sapiens,homo sapiens,NaN,NaN,influenza a virus,homo sapiens,homo sapiens,"Littler, D.R., Rossjohn, J.",2.3,X-RAY DIFFRACTION,0.219,0.181,NaN,NaN,NaN,NaN,True
11,5wkh,J,I,NaN,NaN,abTCR,0,H,peptide,gts3 peptide,NaN,MH1,F,G,39.564,TRBV11,TRAV30,NaN,NaN,IMMUNE SYSTEM,09/20/17,D30 TCR in complex with HLA-A*11:01-GTS3,homo sapiens,homo sapiens,NaN,NaN,dengue virus 3,homo sapiens,homo sapiens,"Gras, S., Rossjohn, J.",3.2,X-RAY DIFFRACTION,0.246,0.177,NaN,NaN,NaN,NaN,True
13,7t2b,T,S,NaN,NaN,abTCR,0,R,peptide,pneumolysin-derived peptide,NaN,MH2,P,Q,36.809,TRBV6,TRAV17,NaN,NaN,IMMUNE SYSTEM,12/28/22,Crystal structure of the 5F TCR in complex with HLA-DP4-Ply,homo sapiens,homo sapiens,NaN,NaN,streptococcus pneumoniae,homo sapiens,homo sapiens,"Ciacchi, L., Farenc, C., Petersen, J., Reid, H.H., Rossjohn, J.",2.8,X-RAY DIFFRACTION,0.250,0.216,NaN,NaN,NaN,NaN,True

In [26]:
df['pdb'].rename('STCRDab').to_csv('STCRDab/STCRDab_pdb.csv', index=False)

In [27]:
with open("STCRDab/3.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['pdb'].tolist())]))

In [ ]:
df.set_index('pdb')['compound'].str.upper().str.split().apply(lambda row: [i for i in row if 'HLA' in i]).str[0].rename('STCRDab_compound').to_csv('STCRDab/STCRDab_hla.csv')

### extract human pdb from STCRDab webpage
link [https://opig.stats.ox.ac.uk/webapps/stcrdab-stcrpred/Browser?all=true]

In [29]:
import requests
from bs4 import BeautifulSoup

response = requests.get("https://opig.stats.ox.ac.uk/webapps/stcrdab-stcrpred/Browser?all=true")

structures = BeautifulSoup(response.content, 'html.parser').find('table').findAll('tr')[1:]

pdb_df = pd.DataFrame([[cell.text for cell in row.findAll('td')[:6]] for row in structures], columns=['PDB', 'Species', 'Method', 'Resolution', 'Affinity', 'TCR_Chains'])

pdb_df.to_csv("STCRDab/pdb.csv", index=False)
print(f"pdb types: {len(pdb_df)}")

pdb types: 634

/tmp/ipykernel_62020/3949048119.py:6: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  structures = BeautifulSoup(response.content, 'html.parser').find('table').findAll('tr')[1:]
/tmp/ipykernel_62020/3949048119.py:8: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  pdb_df = pd.DataFrame([[cell.text for cell in row.findAll('td')[:6]] for row in structures], columns=['PDB', 'Species', 'Method', 'Resolution', 'Affinity', 'TCR_Chains'])