In [44]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('max_colwidth', 100)

In [45]:
# !mkdir TCR3d
# !wget https://tcr3d.ibbr.umd.edu/static/download/tcr_complexes_data.tsv -O TCR3d/TCR3d_raw.tsv

In [46]:
df = pd.read_csv("TCR3d/TCR3d_raw.tsv", sep='\t', dtype=object)
print(f"TCR3d database has {len(df)} records has TCR-peptide-MHC complex structures")
df.head()

TCR3d database has 350 records has TCR-peptide-MHC complex structures

,PDB_ID,TCR_complex,TCR_name,TCR_organism,Epitope,MHC_allele,TRAV_gene,TRBV_gene,CDR1_alpha,CDR2_alpha,CDR3_alpha,CDR1_beta,CDR2_beta,CDR3_beta,Docking_angle,Incident_angle,Buried_surface_area,Shape_complementarity,Release_date,Resolution,Pubmed
0,1ao7,CLASSI,A6,Human,LLFGYPVYV,HLA-A*02,TRAV12-2,TRBV6-5,TYSDRGSQSFF,MSIYSNGDK,CAVTTDSWGKLQF,AQDMNHEYMS,HYSVGAGITD,CASRPGLAGGRPEQYF,33.5,11.0,1964.0,0.64,1997-09-17,2.6,8906788
1,1bd2,CLASSI,B7,Human,LLFGYPVYV,HLA-A*02,TRAV29/DV5,TRBV6-5,DYTNSMFDYFL,ISISSIKD,CAAMEGAQKLVF,AQDMNHEYMS,HYSVGAGITD,CASSYPGGGFYEQYF,48.5,11.8,1871.4,0.64,1998-08-19,2.5,9586631
2,1d9k,CLASSII,D10,Mouse,GNSHRGAIEWEGIESG,I-Ak,TRAV14D-2,TRBV13-2,SYEDSTFDYFP,IAISLVSNKK,CAATGSFNKLTF,NQTNNHNNMY,HYSYGAGSTE,CASGGQGRAEQFF,53.4,6.9,1993.3,0.7,1999-12-15,3.2,10583947
3,1fo0,CLASSI,BM3.3,Mouse,INFDFNTI,H2-Kb,TRAV16,TRBV1,VYETQDSSYFLF,IRQDSYKKE,CAMRGDYGGSGNKLIF,ILKNSQYPWMS,FTLRSPGDKEV,CTCSADRVGNTLYF,41.3,12.4,1375.0,0.6,2000-10-02,2.5,11017099
4,1fyt,CLASSII,HA1.7,Human,PKYVKQNTLKLAT,HLA-DR1,TRAV8-4,TRBV28,NYSSSVPPYLF,LKYTSAATLVK,CAVSESPFGNEKLTF,VQDMDHENMF,YFSYDVKMKE,CASSSTGLPYGYTF,47.2,2.8,2086.4,0.56,2000-11-08,2.6,11060013

In [47]:
with open("TCR3d/0.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['PDB_ID'].tolist())]))

## 1. Fill empty values in MHC_allele

In [48]:
df.loc[df['PDB_ID'].isin(['8rj5', '8yiv', '8yj2', '9c3e']), 'MHC_allele'] = 'HLA'
df['PDB_ID'] = df['PDB_ID'].str.lower()

print(f"TCR3d database has {len(df)} rows matched rules")
df.loc[df['PDB_ID'].isin(['8rj5', '8yiv', '8yj2', '9c3e'])]

TCR3d database has 350 rows matched rules

,PDB_ID,TCR_complex,TCR_name,TCR_organism,Epitope,MHC_allele,TRAV_gene,TRBV_gene,CDR1_alpha,CDR2_alpha,CDR3_alpha,CDR1_beta,CDR2_beta,CDR3_beta,Docking_angle,Incident_angle,Buried_surface_area,Shape_complementarity,Release_date,Resolution,Pubmed
323,8rj5,CLASSI,P1-15,Human,NYNYLYRLF,HLA,TRAV12-1,TRBV6-1,TYSNSASQSFF,MSVYSSGN,CVVNMLRNSGYALNF,AQDMNHNSMY,YYSASEGTTD,CASSESGGYEQYF,50.0,4.9,1506.1,0.672,2025-01-01,3.02,NaN
347,8yiv,CLASSI,N17.1.2,Human,ILDTAGKEEY,HLA,TRDV1,TRBV27,LYETSWWSYYIF,IRQGSDEQ,CALGDTAGKSTF,SQNMNHEYMS,YYSMNVEVTD,CASSLVSTPLPKETQYF,28.1,5.0,NaN,0.739,2024-12-04,2.101,39576860
348,8yj2,CLASSI,N17.1.2,Human,ILDTAGREEY,HLA,TRDV1,TRBV27,LYETSWWSYYIF,IRQGSDEQ,CALGDTAGKSTF,SQNMNHEYMS,YYSMNVEVTD,CASSLVSTPLPKETQYF,28.1,7.1,2150.4,0.742,2024-12-04,2.261,39576860
349,9c3e,CLASSI,1G4,Human,SLLMWITQV,HLA,TRAV21,TRBV6-5,SFTDSAIYNLQ,LLIQSSQREQ,CAVRPLYGGSYIPTF,AQDMNHEYMS,HYSVGAGITD,CASSYVGNTGELFF,NaN,NaN,NaN,0.525,2024-10-02,3.5,37662363

In [49]:
with open("TCR3d/1.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['PDB_ID'].tolist())]))

## 2. PDB drop duplicates

In [50]:
df = df.drop_duplicates(subset=['PDB_ID'])
print(f"TCR3d database has: {len(df)} unique PDB")
df.head()

TCR3d database has: 350 unique PDB

,PDB_ID,TCR_complex,TCR_name,TCR_organism,Epitope,MHC_allele,TRAV_gene,TRBV_gene,CDR1_alpha,CDR2_alpha,CDR3_alpha,CDR1_beta,CDR2_beta,CDR3_beta,Docking_angle,Incident_angle,Buried_surface_area,Shape_complementarity,Release_date,Resolution,Pubmed
0,1ao7,CLASSI,A6,Human,LLFGYPVYV,HLA-A*02,TRAV12-2,TRBV6-5,TYSDRGSQSFF,MSIYSNGDK,CAVTTDSWGKLQF,AQDMNHEYMS,HYSVGAGITD,CASRPGLAGGRPEQYF,33.5,11.0,1964.0,0.64,1997-09-17,2.6,8906788
1,1bd2,CLASSI,B7,Human,LLFGYPVYV,HLA-A*02,TRAV29/DV5,TRBV6-5,DYTNSMFDYFL,ISISSIKD,CAAMEGAQKLVF,AQDMNHEYMS,HYSVGAGITD,CASSYPGGGFYEQYF,48.5,11.8,1871.4,0.64,1998-08-19,2.5,9586631
2,1d9k,CLASSII,D10,Mouse,GNSHRGAIEWEGIESG,I-Ak,TRAV14D-2,TRBV13-2,SYEDSTFDYFP,IAISLVSNKK,CAATGSFNKLTF,NQTNNHNNMY,HYSYGAGSTE,CASGGQGRAEQFF,53.4,6.9,1993.3,0.7,1999-12-15,3.2,10583947
3,1fo0,CLASSI,BM3.3,Mouse,INFDFNTI,H2-Kb,TRAV16,TRBV1,VYETQDSSYFLF,IRQDSYKKE,CAMRGDYGGSGNKLIF,ILKNSQYPWMS,FTLRSPGDKEV,CTCSADRVGNTLYF,41.3,12.4,1375.0,0.6,2000-10-02,2.5,11017099
4,1fyt,CLASSII,HA1.7,Human,PKYVKQNTLKLAT,HLA-DR1,TRAV8-4,TRBV28,NYSSSVPPYLF,LKYTSAATLVK,CAVSESPFGNEKLTF,VQDMDHENMF,YFSYDVKMKE,CASSSTGLPYGYTF,47.2,2.8,2086.4,0.56,2000-11-08,2.6,11060013

In [51]:
with open("TCR3d/2.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['PDB_ID'].tolist())]))

## 3. Select HLA

In [52]:
df = df.loc[df['MHC_allele'].str.upper().str[:3]=='HLA']
print(f"TCR3d database has: {len(df)} unique human PDB")
df.head()

TCR3d database has: 279 unique human PDB

,PDB_ID,TCR_complex,TCR_name,TCR_organism,Epitope,MHC_allele,TRAV_gene,TRBV_gene,CDR1_alpha,CDR2_alpha,CDR3_alpha,CDR1_beta,CDR2_beta,CDR3_beta,Docking_angle,Incident_angle,Buried_surface_area,Shape_complementarity,Release_date,Resolution,Pubmed
0,1ao7,CLASSI,A6,Human,LLFGYPVYV,HLA-A*02,TRAV12-2,TRBV6-5,TYSDRGSQSFF,MSIYSNGDK,CAVTTDSWGKLQF,AQDMNHEYMS,HYSVGAGITD,CASRPGLAGGRPEQYF,33.5,11.0,1964.0,0.64,1997-09-17,2.6,8906788
1,1bd2,CLASSI,B7,Human,LLFGYPVYV,HLA-A*02,TRAV29/DV5,TRBV6-5,DYTNSMFDYFL,ISISSIKD,CAAMEGAQKLVF,AQDMNHEYMS,HYSVGAGITD,CASSYPGGGFYEQYF,48.5,11.8,1871.4,0.64,1998-08-19,2.5,9586631
4,1fyt,CLASSII,HA1.7,Human,PKYVKQNTLKLAT,HLA-DR1,TRAV8-4,TRBV28,NYSSSVPPYLF,LKYTSAATLVK,CAVSESPFGNEKLTF,VQDMDHENMF,YFSYDVKMKE,CASSSTGLPYGYTF,47.2,2.8,2086.4,0.56,2000-11-08,2.6,11060013
6,1j8h,CLASSII,HA1.7,Human,PKYVKQNTLKLAT,HLA-DR4,TRAV8-4,TRBV28,NYSSSVPPYLF,LKYTSAATLVK,CAVSESPFGNEKLTF,VQDMDHENMF,YFSYDVKMKE,CASSSTGLPYGYTF,48.9,1.0,2111.4,0.56,2002-03-13,2.4,11877480
8,1lp9,CLASSI,AHIII,Mouse,ALWGFFPVL,HLA-A*02,TRAV12D-2,TRBV13-3,TYQSTYSPFLF,LKSFTDNKRP,CALFLASSSFSKLVF,HQTNNHDYMY,HYSYVADSTE,CASSDWVSYEQYF,67.3,2.1,1979.8,0.71,2003-11-11,2.0,14563323

In [53]:
df['PDB_ID'].rename('TCR3d').to_csv('TCR3d/TCR3d_pdb.csv', index=False)

In [54]:
with open("TCR3d/3.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['PDB_ID'].tolist())]))

In [55]:
df[['MHC_allele', 'PDB_ID']].rename(columns={'PDB_ID':'pdb', 'MHC_allele': 'TCR3d_MHC_allele'}).set_index('pdb').to_csv('TCR3d/TCR3d_hla.csv')