In [1]:
import pandas as pd
pd.set_option('display.max_columns', None) 
pd.set_option('display.width', None)
pd.set_option('max_colwidth', 100)

In [2]:
# !wget https://pgx.zju.edu.cn/download.trait/Interactive_TCR-pMHC_Pairs.zip -P TRAIT
# !unzip TRAIT/Interactive_TCR-pMHC_Pairs.zip -d TRAIT/

In [3]:
df = pd.read_excel("TRAIT/Interactive_TCR-pMHC_Pairs.xlsx", dtype=object)
df.to_csv('TRAIT/TRAIT_raw.csv', index=False)
print(f"TRAIT database has: {len(df)} records")
df.head()

TRAIT database has: 51438 records

,CDR3a,TRAV,TRAJ,CDR3b,TRBV,TRBJ,Species,Sequencing_Methods,MHC_A,MHC_B,MHC_class,Epitope,Gene,Epitope_species,Binding,Identification_Methods,Verification_Methods,KD,deltaG,Affinity_Method,Structure,Structure_Method,PMID,Donor,Tissue,Category,Year,ID
0,CAGATGNTGKLIF,TRAV27*01,TRAJ37*01,CASSTRGAYEQYF,TRBV19*01,TRBJ2-7*01,Homo Sapiens,Sanger,HLA-A*02:01,B2M,MHCI,GILGFVFTL,M,InfluenzaA,TRUE,"cultured-T-cells,antigen-expressing-targets",NaN,NaN,NaN,NaN,NaN,NaN,PMID:7807026,NaN,PBMC,Flu,1995,1
1,CAGAGSQGNLIF,TRAV27*01,TRAJ42*01,CASSSRSSYEQYF,TRBV19*01,TRBJ2-7*01,Homo Sapiens,Sanger,HLA-A*02:01,B2M,MHCI,GILGFVFTL,M,InfluenzaA,TRUE,"cultured-T-cells,antigen-expressing-targets",NaN,NaN,NaN,NaN,NaN,NaN,PMID:7807026,NaN,PBMC,Flu,1995,2
2,CAVNSYYNQGGKLIF,TRAV12-2*01,TRAJ23*01,CSVLQGSPYEQYF,TRBV29-1*01,TRBJ2-7*01,Homo Sapiens,Sanger,HLA-A*02:01,B2M,MHCI,GILGFVFTL,M,InfluenzaA,TRUE,"cultured-T-cells,antigen-expressing-targets",NaN,NaN,NaN,NaN,NaN,NaN,PMID:7807026,NaN,PBMC,Flu,1995,3
3,CAGGGSQGNLIF,TRAV27*01,TRAJ42*01,CASSIRSSYEQYF,TRBV19*01,TRBJ2-7*01,Homo Sapiens,Sanger,HLA-A*02:01,B2M,MHCI,GILGFVFTL,M,InfluenzaA,TRUE,"cultured-T-cells,antigen-expressing-targets",NaN,NaN,NaN,NaN,NaN,NaN,PMID:7807026,NaN,PBMC,Flu,1995,4
4,CLVGGLARDMRF,TRAV4*01,TRAJ43*01,CSVALGSDTGELFF,TRBV29-1*01,TRBJ2-2*01,Homo Sapiens,NaN,HLA-DQA1*05,HLA-DQB1*02,MHCII,LQPFPQPELPYGSGGS,DQ2-GLIA-OMEGA1,Homo Sapiens,TRUE,NaN,NaN,0.37,NaN,NaN,7sg2,XRD,unpublished,NaN,NaN,Cancer,2022,5

In [4]:
with open("TRAIT/0.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['Structure'].tolist())]))

## 1. Remove rows without PDB information

In [5]:
df = df.dropna(subset=['Structure'])
df['Structure'] = df['Structure'].str.lower()

print(f"TRAIT database has {len(df)} rows incloud PDB information")
df.head()

TRAIT database has 201 rows incloud PDB information

,CDR3a,TRAV,TRAJ,CDR3b,TRBV,TRBJ,Species,Sequencing_Methods,MHC_A,MHC_B,MHC_class,Epitope,Gene,Epitope_species,Binding,Identification_Methods,Verification_Methods,KD,deltaG,Affinity_Method,Structure,Structure_Method,PMID,Donor,Tissue,Category,Year,ID
4,CLVGGLARDMRF,TRAV4*01,TRAJ43*01,CSVALGSDTGELFF,TRBV29-1*01,TRBJ2-2*01,Homo Sapiens,NaN,HLA-DQA1*05,HLA-DQB1*02,MHCII,LQPFPQPELPYGSGGS,DQ2-GLIA-OMEGA1,Homo Sapiens,TRUE,NaN,NaN,0.37,NaN,NaN,7sg2,XRD,unpublished,NaN,NaN,Cancer,2022,5
26,CALSGGTSYGKLTF,TRAV9-2*01,TRAJ52*01,CASSQGQDTEAFF,TRBV7-3*01,TRBJ1-1*01,Homo Sapiens,NaN,HLA-DQA1*05,HLA-DQB1*02,MHCII,QPFPQPEQPFP,DQ2-GLIA-OMEGA1,Homo Sapiens,TRUE,NaN,NaN,NaN,NaN,NaN,7sg0,XRD,unpublished,NaN,NaN,Cancer,2022,27
27,CAVNRDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,Homo Sapiens,Singlecell,HLA-A*02:01,B2M,MHCI,YLQPRTFLL,Spike,SARS-CoV-2,TRUE,NaN,NaN,NaN,NaN,NaN,7rtr,XRD,PMID:34685626,NaN,NaN,COVID-19,2021,28
28,CLVGGAYTGGFKTIF,TRAV4*01,TRAJ9*01,CASSLVAETYEQYF,TRBV11-2*01,TRBJ2-7*01,Homo Sapiens,NaN,HLA-A*03:01,B2M,MHCI,ALHGGWTTK,PIK3CA,Homo Sapiens,TRUE,NaN,NaN,NaN,NaN,NaN,7rrg,XRD,unpublished,NaN,NaN,Cancer,2022,29
62,CALDIYPHDMRF,TRAV6*01,TRAJ43*01,CASSLDPGDTGELFF,TRBV11-2*01,TRBJ2-2*01,Homo Sapiens,NaN,HLA-A*02,B2M,MHCI,HMTEVVRHC,TP53,Homo Sapiens,TRUE,"peptide-restimulation,tetramer-sort",NaN,6.4,NaN,NaN,7rm4,XRD,PMID:35124005,NaN,NaN,Cancer,2022,63

In [6]:
with open("TRAIT/1.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['Structure'].tolist())]))

## 2. PDB drop duplicates

In [7]:
df = df.drop_duplicates(subset=['Structure'])
print(f"TRAIT database has: {len(df)} unique PDB")
df.head()

TRAIT database has: 192 unique PDB

,CDR3a,TRAV,TRAJ,CDR3b,TRBV,TRBJ,Species,Sequencing_Methods,MHC_A,MHC_B,MHC_class,Epitope,Gene,Epitope_species,Binding,Identification_Methods,Verification_Methods,KD,deltaG,Affinity_Method,Structure,Structure_Method,PMID,Donor,Tissue,Category,Year,ID
4,CLVGGLARDMRF,TRAV4*01,TRAJ43*01,CSVALGSDTGELFF,TRBV29-1*01,TRBJ2-2*01,Homo Sapiens,NaN,HLA-DQA1*05,HLA-DQB1*02,MHCII,LQPFPQPELPYGSGGS,DQ2-GLIA-OMEGA1,Homo Sapiens,TRUE,NaN,NaN,0.37,NaN,NaN,7sg2,XRD,unpublished,NaN,NaN,Cancer,2022,5
26,CALSGGTSYGKLTF,TRAV9-2*01,TRAJ52*01,CASSQGQDTEAFF,TRBV7-3*01,TRBJ1-1*01,Homo Sapiens,NaN,HLA-DQA1*05,HLA-DQB1*02,MHCII,QPFPQPEQPFP,DQ2-GLIA-OMEGA1,Homo Sapiens,TRUE,NaN,NaN,NaN,NaN,NaN,7sg0,XRD,unpublished,NaN,NaN,Cancer,2022,27
27,CAVNRDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,Homo Sapiens,Singlecell,HLA-A*02:01,B2M,MHCI,YLQPRTFLL,Spike,SARS-CoV-2,TRUE,NaN,NaN,NaN,NaN,NaN,7rtr,XRD,PMID:34685626,NaN,NaN,COVID-19,2021,28
28,CLVGGAYTGGFKTIF,TRAV4*01,TRAJ9*01,CASSLVAETYEQYF,TRBV11-2*01,TRBJ2-7*01,Homo Sapiens,NaN,HLA-A*03:01,B2M,MHCI,ALHGGWTTK,PIK3CA,Homo Sapiens,TRUE,NaN,NaN,NaN,NaN,NaN,7rrg,XRD,unpublished,NaN,NaN,Cancer,2022,29
62,CALDIYPHDMRF,TRAV6*01,TRAJ43*01,CASSLDPGDTGELFF,TRBV11-2*01,TRBJ2-2*01,Homo Sapiens,NaN,HLA-A*02,B2M,MHCI,HMTEVVRHC,TP53,Homo Sapiens,TRUE,"peptide-restimulation,tetramer-sort",NaN,6.4,NaN,NaN,7rm4,XRD,PMID:35124005,NaN,NaN,Cancer,2022,63

In [8]:
with open("TRAIT/2.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['Structure'].tolist())]))

## 3. Keep human MHC

In [9]:
print("MHC_A statistic")
df['MHC_A'].str[:3].value_counts()

MHC_A statistic

MHC_A
HLA    192
Name: count, dtype: int64

In [10]:
print("MHC_B statistic")
df['MHC_B'].str[:3].value_counts()

MHC_B statistic

MHC_B
B2M    149
HLA     43
Name: count, dtype: int64

In [11]:
df = df.loc[df['MHC_A'].str[:3]=='HLA']
print(f"TRAIT database has: {len(df)} unique human PDB")
df.head()

TRAIT database has: 192 unique human PDB

,CDR3a,TRAV,TRAJ,CDR3b,TRBV,TRBJ,Species,Sequencing_Methods,MHC_A,MHC_B,MHC_class,Epitope,Gene,Epitope_species,Binding,Identification_Methods,Verification_Methods,KD,deltaG,Affinity_Method,Structure,Structure_Method,PMID,Donor,Tissue,Category,Year,ID
4,CLVGGLARDMRF,TRAV4*01,TRAJ43*01,CSVALGSDTGELFF,TRBV29-1*01,TRBJ2-2*01,Homo Sapiens,NaN,HLA-DQA1*05,HLA-DQB1*02,MHCII,LQPFPQPELPYGSGGS,DQ2-GLIA-OMEGA1,Homo Sapiens,TRUE,NaN,NaN,0.37,NaN,NaN,7sg2,XRD,unpublished,NaN,NaN,Cancer,2022,5
26,CALSGGTSYGKLTF,TRAV9-2*01,TRAJ52*01,CASSQGQDTEAFF,TRBV7-3*01,TRBJ1-1*01,Homo Sapiens,NaN,HLA-DQA1*05,HLA-DQB1*02,MHCII,QPFPQPEQPFP,DQ2-GLIA-OMEGA1,Homo Sapiens,TRUE,NaN,NaN,NaN,NaN,NaN,7sg0,XRD,unpublished,NaN,NaN,Cancer,2022,27
27,CAVNRDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,Homo Sapiens,Singlecell,HLA-A*02:01,B2M,MHCI,YLQPRTFLL,Spike,SARS-CoV-2,TRUE,NaN,NaN,NaN,NaN,NaN,7rtr,XRD,PMID:34685626,NaN,NaN,COVID-19,2021,28
28,CLVGGAYTGGFKTIF,TRAV4*01,TRAJ9*01,CASSLVAETYEQYF,TRBV11-2*01,TRBJ2-7*01,Homo Sapiens,NaN,HLA-A*03:01,B2M,MHCI,ALHGGWTTK,PIK3CA,Homo Sapiens,TRUE,NaN,NaN,NaN,NaN,NaN,7rrg,XRD,unpublished,NaN,NaN,Cancer,2022,29
62,CALDIYPHDMRF,TRAV6*01,TRAJ43*01,CASSLDPGDTGELFF,TRBV11-2*01,TRBJ2-2*01,Homo Sapiens,NaN,HLA-A*02,B2M,MHCI,HMTEVVRHC,TP53,Homo Sapiens,TRUE,"peptide-restimulation,tetramer-sort",NaN,6.4,NaN,NaN,7rm4,XRD,PMID:35124005,NaN,NaN,Cancer,2022,63

In [12]:
# df.to_csv("TRAIT/TRAIT_clean.csv", index=False)

In [13]:
df['Structure'].rename('TRAIT').to_csv('TRAIT/TRAIT_pdb.csv', index=False)

In [ ]:
with open("TRAIT/3.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['Structure'].tolist())]))

In [19]:
df[['Structure', 'MHC_A', 'MHC_B']].rename(columns={'Structure':'pdb', 'MHC_A': 'TRAIT_MHC_A', 'MHC_B': 'TRAIT_MHC_B'}).set_index('pdb').to_csv('TRAIT/TRAIT_hla.csv')