In [1]:
import json
import pandas as pd
pd.set_option('display.max_columns', None) 
pd.set_option('display.width', None)
pd.set_option('max_colwidth', 100)

In [ ]:
# !wget https://github.com/antigenomics/vdjdb-db/releases/download/pyvdjdb-2025-02-21/vdjdb-2025-02-21.zip -P VDJdb
# !unzip VDJdb/vdjdb-2025-02-21.zip -d VDJdb/

In [3]:
df = pd.read_csv("VDJdb/vdjdb-2025-02-21/vdjdb.txt", dtype=object, sep='\t')
print(f"VDJdb database has: {len(df)} records")
df.head()

VDJdb database has: 116740 records

,complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,antigen.gene,antigen.species,reference.id,method,meta,cdr3fix,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp,vdjdb.score
0,0,TRB,CASSIVGGNEQFF,TRBV19*01,TRBJ2-1*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,GILGFVFTL,M,InfluenzaA,PMID:28629751,"{""identification"": ""tetramer-sort "", ""frequency"": ""70.5%"", ""singlecell"": """", ""sequencing"": ""ampl...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": ""MA-EBV-SN"", ""subject.id"": ""donor1"", ""...","{""cdr3"": ""CASSIVGGNEQFF"", ""cdr3_old"": ""CASSIVGGNEQFF"", ""fixNeeded"": false, ""good"": true, ""jCanon...",sort,amplicon,no,no,2
1,0,TRB,CASSMRSTGELFF,TRBV19*01,TRBJ2-2*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,GILGFVFTL,M,InfluenzaA,PMID:28629751,"{""identification"": ""tetramer-sort "", ""frequency"": ""11.0%"", ""singlecell"": """", ""sequencing"": ""ampl...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": ""MA-EBV-SN"", ""subject.id"": ""donor1"", ""...","{""cdr3"": ""CASSMRSTGELFF"", ""cdr3_old"": ""CASSMRSTGELFF"", ""fixNeeded"": false, ""good"": true, ""jCanon...",sort,amplicon,no,no,2
2,0,TRB,CASSIRSAWAQYF,TRBV19*01,TRBJ2-3*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,GILGFVFTL,M,InfluenzaA,PMID:28629751,"{""identification"": ""tetramer-sort "", ""frequency"": ""1.9%"", ""singlecell"": """", ""sequencing"": ""ampli...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": ""MA-EBV-SN IAV-M1"", ""subject.id"": ""don...","{""cdr3"": ""CASSIRSAWAQYF"", ""cdr3_old"": ""CASSIRSAWAQYF"", ""fixNeeded"": false, ""good"": true, ""jCanon...",sort,amplicon,no,no,2
3,0,TRB,CASSQRSTGELFF,TRBV19*01,TRBJ2-2*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,GILGFVFTL,M,InfluenzaA,PMID:28629751,"{""identification"": ""tetramer-sort "", ""frequency"": ""1.7%"", ""singlecell"": """", ""sequencing"": ""ampli...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": ""MA-EBV-SN IAV-M1"", ""subject.id"": ""don...","{""cdr3"": ""CASSQRSTGELFF"", ""cdr3_old"": ""CASSQRSTGELFF"", ""fixNeeded"": false, ""good"": true, ""jCanon...",sort,amplicon,no,no,3
4,0,TRB,CASSIRSSYEQYF,TRBV19*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,GILGFVFTL,M,InfluenzaA,PMID:28629751,"{""identification"": ""tetramer-sort "", ""frequency"": ""0.9%"", ""singlecell"": """", ""sequencing"": ""ampli...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": ""MA-EBV-SN IAV-M1"", ""subject.id"": ""don...","{""cdr3"": ""CASSIRSSYEQYF"", ""cdr3_old"": ""CASSIRSSYEQYF"", ""fixNeeded"": false, ""good"": true, ""jCanon...",sort,amplicon,no,no,3

In [4]:
df['structure.id'] = df['meta'].apply(lambda s: json.loads(s)['structure.id'])

with open("VDJdb/0.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['structure.id'].tolist())]))

## 1. Remove rows without PDB information

In [5]:
df['structure.id'] = df['meta'].apply(lambda s: json.loads(s)['structure.id'])
df = df.loc[df['structure.id'].str.len()==4]
df['structure.id'] = df['structure.id'].str.lower()

print(f"VDJdb database has {len(df)} rows incloud PDB information")
df.head()

VDJdb database has 654 rows incloud PDB information

,complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,antigen.gene,antigen.species,reference.id,method,meta,cdr3fix,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp,vdjdb.score,structure.id
10921,2610,TRA,CLVGEILDNFNKFYF,TRAV4*01,TRAJ21*01,HomoSapiens,HLA-B*07:02,B2M,MHCI,APRGPHGGAASGL,NY-ESO-1,HomoSapiens,PMID:29531227,"{""identification"": ""antigen-loaded-targets"", ""frequency"": """", ""singlecell"": ""yes"", ""sequencing"":...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CLVGEILDNFNKFYF"", ""cdr3_old"": ""CLVGEILDNFNKFYF"", ""fixNeeded"": false, ""good"": true, ""jC...",culture,singlecell,no,no,2,6avf
10922,2610,TRB,CASSQRQEGDTQYF,TRBV28*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,MHCI,APRGPHGGAASGL,NY-ESO-1,HomoSapiens,PMID:29531227,"{""identification"": ""antigen-loaded-targets"", ""frequency"": """", ""singlecell"": ""yes"", ""sequencing"":...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CASSQRQEGDTQYF"", ""cdr3_old"": ""CASSQRQEGDTQYF"", ""fixNeeded"": false, ""good"": true, ""jCan...",culture,singlecell,no,no,2,6avf
10925,2612,TRA,CLVVDQKLVF,TRAV4*01,TRAJ8*01,HomoSapiens,HLA-B*07:02,B2M,MHCI,APRGPHGGAASGL,NY-ESO-1,HomoSapiens,PMID:29531227,"{""identification"": ""antigen-loaded-targets"", ""frequency"": """", ""singlecell"": ""yes"", ""sequencing"":...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CLVVDQKLVF"", ""cdr3_old"": ""CLVVDQKLVF"", ""fixNeeded"": false, ""good"": true, ""jCanonical"":...",culture,singlecell,no,no,2,6avg
10926,2612,TRB,CASSGGHTGSNEQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,MHCI,APRGPHGGAASGL,NY-ESO-1,HomoSapiens,PMID:29531227,"{""identification"": ""antigen-loaded-targets"", ""frequency"": """", ""singlecell"": ""yes"", ""sequencing"":...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CASSGGHTGSNEQFF"", ""cdr3_old"": ""CASSGGHTGSNEQFF"", ""fixNeeded"": false, ""good"": true, ""jC...",culture,singlecell,no,no,2,6avg
11014,2614,TRA,CAVLSSGGSNYKLTF,TRAV21*01,TRAJ53*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,YLEPGPVTA,gp100,HomoSapiens,PMID:26917722,"{""identification"": ""tetramer sort"", ""frequency"": """", ""singlecell"": """", ""sequencing"": ""sanger"", ""...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CAVLSSGGSNYKLTF"", ""cdr3_old"": ""CAVLSSGGSNYKLTF"", ""fixNeeded"": false, ""good"": true, ""jC...",sort,sanger,no,no,2,5eu6

In [6]:
with open("VDJdb/1.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['structure.id'].tolist())]))

## 2. PDB drop duplicates

In [7]:
df = df.drop_duplicates(subset=['structure.id'])
print(f"VDJdb database has: {len(df)} unique PDB")
df.head()

VDJdb database has: 263 unique PDB

,complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,antigen.gene,antigen.species,reference.id,method,meta,cdr3fix,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp,vdjdb.score,structure.id
10921,2610,TRA,CLVGEILDNFNKFYF,TRAV4*01,TRAJ21*01,HomoSapiens,HLA-B*07:02,B2M,MHCI,APRGPHGGAASGL,NY-ESO-1,HomoSapiens,PMID:29531227,"{""identification"": ""antigen-loaded-targets"", ""frequency"": """", ""singlecell"": ""yes"", ""sequencing"":...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CLVGEILDNFNKFYF"", ""cdr3_old"": ""CLVGEILDNFNKFYF"", ""fixNeeded"": false, ""good"": true, ""jC...",culture,singlecell,no,no,2,6avf
10925,2612,TRA,CLVVDQKLVF,TRAV4*01,TRAJ8*01,HomoSapiens,HLA-B*07:02,B2M,MHCI,APRGPHGGAASGL,NY-ESO-1,HomoSapiens,PMID:29531227,"{""identification"": ""antigen-loaded-targets"", ""frequency"": """", ""singlecell"": ""yes"", ""sequencing"":...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CLVVDQKLVF"", ""cdr3_old"": ""CLVVDQKLVF"", ""fixNeeded"": false, ""good"": true, ""jCanonical"":...",culture,singlecell,no,no,2,6avg
11014,2614,TRA,CAVLSSGGSNYKLTF,TRAV21*01,TRAJ53*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,YLEPGPVTA,gp100,HomoSapiens,PMID:26917722,"{""identification"": ""tetramer sort"", ""frequency"": """", ""singlecell"": """", ""sequencing"": ""sanger"", ""...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CAVLSSGGSNYKLTF"", ""cdr3_old"": ""CAVLSSGGSNYKLTF"", ""fixNeeded"": false, ""good"": true, ""jC...",sort,sanger,no,no,2,5eu6
19601,6459,TRA,CGLGDAGNMLTF,TRAV30*01,TRAJ39*01,HomoSapiens,HLA-A*11:01,B2M,MHCI,GTSGSPIVNR,NS3,DENV,PMID:28945243,"{""identification"": ""tetramer-sort,cultured-T-cells"", ""frequency"": """", ""singlecell"": """", ""sequenc...","{""study.id"": """", ""cell.subset"": ""CD3+CD8+CD14-CD19-"", ""subject.cohort"": """", ""subject.id"": """", ""r...","{""cdr3"": ""CGLGDAGNMLTF"", ""cdr3_old"": ""CGLGDAGNMLT"", ""fixNeeded"": true, ""good"": true, ""jCanonical...",sort,amplicon,no,no,2,5wkf
19603,6460,TRA,CGLGDAGNMLTF,TRAV30*01,TRAJ39*01,HomoSapiens,HLA-A*11:01,B2M,MHCI,GTSGSPIINR,NS3,DENV,PMID:28945243,"{""identification"": ""tetramer-sort,cultured-T-cells"", ""frequency"": """", ""singlecell"": """", ""sequenc...","{""study.id"": """", ""cell.subset"": ""CD3+CD8+CD14-CD19-"", ""subject.cohort"": """", ""subject.id"": """", ""r...","{""cdr3"": ""CGLGDAGNMLTF"", ""cdr3_old"": ""CGLGDAGNMLT"", ""fixNeeded"": true, ""good"": true, ""jCanonical...",sort,amplicon,no,no,2,5wkh

In [ ]:
with open("VDJdb/2.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['structure.id'].tolist())]))

## 3. Keep human MHC

In [9]:
print("mhc.a statistic")
df['mhc.a'].str[:3].value_counts()

mhc.a statistic

mhc.a
HLA    203
H-2     60
Name: count, dtype: int64

In [10]:
print("mhc.b statistic")
df['mhc.b'].str[:3].value_counts()

mhc.b statistic

mhc.b
B2M    188
HLA     49
H-2     26
Name: count, dtype: int64

In [11]:
df = df.loc[df['mhc.a'].str[:3]=='HLA']
print(f"VDJdb database has: {len(df)} unique human PDB")
df.head()

VDJdb database has: 203 unique human PDB

,complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,antigen.gene,antigen.species,reference.id,method,meta,cdr3fix,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp,vdjdb.score,structure.id
10921,2610,TRA,CLVGEILDNFNKFYF,TRAV4*01,TRAJ21*01,HomoSapiens,HLA-B*07:02,B2M,MHCI,APRGPHGGAASGL,NY-ESO-1,HomoSapiens,PMID:29531227,"{""identification"": ""antigen-loaded-targets"", ""frequency"": """", ""singlecell"": ""yes"", ""sequencing"":...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CLVGEILDNFNKFYF"", ""cdr3_old"": ""CLVGEILDNFNKFYF"", ""fixNeeded"": false, ""good"": true, ""jC...",culture,singlecell,no,no,2,6avf
10925,2612,TRA,CLVVDQKLVF,TRAV4*01,TRAJ8*01,HomoSapiens,HLA-B*07:02,B2M,MHCI,APRGPHGGAASGL,NY-ESO-1,HomoSapiens,PMID:29531227,"{""identification"": ""antigen-loaded-targets"", ""frequency"": """", ""singlecell"": ""yes"", ""sequencing"":...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CLVVDQKLVF"", ""cdr3_old"": ""CLVVDQKLVF"", ""fixNeeded"": false, ""good"": true, ""jCanonical"":...",culture,singlecell,no,no,2,6avg
11014,2614,TRA,CAVLSSGGSNYKLTF,TRAV21*01,TRAJ53*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,YLEPGPVTA,gp100,HomoSapiens,PMID:26917722,"{""identification"": ""tetramer sort"", ""frequency"": """", ""singlecell"": """", ""sequencing"": ""sanger"", ""...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subject.cohort"": """", ""subject.id"": """", ""replica.id"": """"...","{""cdr3"": ""CAVLSSGGSNYKLTF"", ""cdr3_old"": ""CAVLSSGGSNYKLTF"", ""fixNeeded"": false, ""good"": true, ""jC...",sort,sanger,no,no,2,5eu6
19601,6459,TRA,CGLGDAGNMLTF,TRAV30*01,TRAJ39*01,HomoSapiens,HLA-A*11:01,B2M,MHCI,GTSGSPIVNR,NS3,DENV,PMID:28945243,"{""identification"": ""tetramer-sort,cultured-T-cells"", ""frequency"": """", ""singlecell"": """", ""sequenc...","{""study.id"": """", ""cell.subset"": ""CD3+CD8+CD14-CD19-"", ""subject.cohort"": """", ""subject.id"": """", ""r...","{""cdr3"": ""CGLGDAGNMLTF"", ""cdr3_old"": ""CGLGDAGNMLT"", ""fixNeeded"": true, ""good"": true, ""jCanonical...",sort,amplicon,no,no,2,5wkf
19603,6460,TRA,CGLGDAGNMLTF,TRAV30*01,TRAJ39*01,HomoSapiens,HLA-A*11:01,B2M,MHCI,GTSGSPIINR,NS3,DENV,PMID:28945243,"{""identification"": ""tetramer-sort,cultured-T-cells"", ""frequency"": """", ""singlecell"": """", ""sequenc...","{""study.id"": """", ""cell.subset"": ""CD3+CD8+CD14-CD19-"", ""subject.cohort"": """", ""subject.id"": """", ""r...","{""cdr3"": ""CGLGDAGNMLTF"", ""cdr3_old"": ""CGLGDAGNMLT"", ""fixNeeded"": true, ""good"": true, ""jCanonical...",sort,amplicon,no,no,2,5wkh

In [ ]:
df['structure.id'].rename('VDJdb').to_csv('VDJdb/VDJdb_pdb.csv', index=False)

In [ ]:
with open("VDJdb/3.pdb.txt", 'w') as f:
    f.write('\n'.join([str(i) for i in set(df['structure.id'].tolist())]))

In [22]:
df[['structure.id', 'mhc.a', 'mhc.b']].rename(columns={'structure.id':'pdb', 'mhc.a':'VDJdb_mhc.a', 'mhc.b': 'VDJdb_mhc.b'}).set_index('pdb').to_csv('VDJdb/VDJdb_hla.csv')